# **Collective learning project -  WikiRAG-TR dataset - e5**
# **Zainab Elfatih Mohamed MAlik - 24501096**

### **0. Prepare libraries**

In [ ]:
!pip install datasets
!pip install transformers torch datasets
!pip install tqdm
!pip install faiss-cpu
!pip install evaluate

Requirement already satisfied: datasets in /usr/local/lib/python3.10/dist-packages (3.2.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from datasets) (3.16.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from datasets) (1.26.4)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.10/dist-packages (from datasets) (17.0.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.10/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.10/dist-packages (from datasets) (2.32.3)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.10/dist-packages (from datasets) (4.67.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.10/dist-packages (from datasets) (3.5.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.10/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2024.9.0,>=2023.1.0 in /usr/local/lib/python3.10/dist-packages (from fsspec[http]<=2024.9.0,>=2023.1.0->datasets) (2024.9.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.10/dist-packages (from datasets) (3.11.11)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.10/dist-packages (from datasets) (0.27.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from datasets) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from datasets) (6.0.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (2.4.4)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.3.2)
Requirement already satisfied: async-timeout<6.0,>=4.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (4.0.3)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (24.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (0.2.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.18.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.23.0->datasets) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.32.2->datasets) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.32.2->datasets) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.32.2->datasets) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.32.2->datasets) (2024.12.14)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2024.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: transformers in /usr/local/lib/python3.10/dist-packages (4.47.1)
Requirement already satisfied: torch in /usr/local/lib/python3.10/dist-packages (2.5.1+cu121)
Requirement already satisfied: datasets in /usr/local/lib/python3.10/dist-packages (3.2.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from transformers) (3.16.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.24.0 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.27.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from transformers) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from transformers) (2.32.3)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.21.0)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.5.1)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.10/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.10/dist-packages (from torch) (4.12.2)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch) (3.1.5)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from torch) (2024.9.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.10/dist-packages (from torch) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy==1.13.1->torch) (1.3.0)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.10/dist-packages (from datasets) (17.0.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.10/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: xxhash in /usr/local/lib/python3.10/dist-packages (from datasets) (3.5.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.10/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.10/dist-packages (from datasets) (3.11.11)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (2.4.4)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.3.2)
Requirement already satisfied: async-timeout<6.0,>=4.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (4.0.3)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (24.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (0.2.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.18.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (2024.12.14)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch) (3.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2024.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (4.67.1)
Requirement already satisfied: faiss-cpu in /usr/local/lib/python3.10/dist-packages (1.9.0.post1)
Requirement already satisfied: numpy<3.0,>=1.25.0 in /usr/local/lib/python3.10/dist-packages (from faiss-cpu) (1.26.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from faiss-cpu) (24.2)
Requirement already satisfied: evaluate in /usr/local/lib/python3.10/dist-packages (0.4.3)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from evaluate) (3.2.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from evaluate) (1.26.4)
Requirement already satisfied: dill in /usr/local/lib/python3.10/dist-packages (from evaluate) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from evaluate) (2.2.2)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.10/dist-packages (from evaluate) (2.32.3)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.10/dist-packages (from evaluate) (4.67.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.10/dist-packages (from evaluate) (3.5.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.10/dist-packages (from evaluate) (0.70.16)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.10/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (2024.9.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from evaluate) (0.27.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from evaluate) (24.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from datasets>=2.0.0->evaluate) (3.16.1)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.10/dist-packages (from datasets>=2.0.0->evaluate) (17.0.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.10/dist-packages (from datasets>=2.0.0->evaluate) (3.11.11)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from datasets>=2.0.0->evaluate) (6.0.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->evaluate) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->evaluate) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->evaluate) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->evaluate) (2024.12.14)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas->evaluate) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->evaluate) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas->evaluate) (2024.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (2.4.4)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.3.2)
Requirement already satisfied: async-timeout<6.0,>=4.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (4.0.3)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (24.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (0.2.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.18.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.17.0)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
from datasets import load_dataset
import pandas as pd
import json
from transformers import AutoTokenizer, AutoModel
import torch
from tqdm import tqdm
import numpy as np
import faiss
from transformers import AutoModelForSequenceClassification, Trainer, TrainingArguments
from sklearn.model_selection import train_test_split
import torch
from tqdm import tqdm
from evaluate import load
import random

## **1. Dataset overview and preprocess**

In [ ]:
ds = load_dataset("Metin/WikiRAG-TR") #load dataset

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

In [ ]:
train_data = ds["train"]
data = pd.DataFrame(train_data) # convert to pandas dataframe
data

,id,question,answer,context,is_negative_response,number_of_articles,ctx_split_points,correct_intro_idx
0,fdb9e733-8b3f-430e-93d4-72c563f2d00c,Bermuda Adaları'nın Birleşik Krallık'a bağlı b...,"Bermuda Adaları, 1609 yılında İngiliz denizci ...","Thingspiel (çoğulu Thingspiele), 1930'larda sa...",0,6,"[374, 1916, 3860, 4309, 4775, 5443]",3
1,cb5dacdf-cb15-49c5-b0a5-8de9bb77cb48,.bm uzantısının kullanımı ne zaman başladı?,.bm uzantısı 2007 yılında kullanıma açıldı.,"Kabulgan – Türk, Altay ve Moğol mitolojisinde ...",0,2,"[266, 398]",1
2,0b827c00-160b-4a1c-9e8f-096208a73892,NKVD'nin Sovyetler Birliği içindeki siyasi bas...,"NKVD, Joseph Stalin yönetimindeki Büyük Temizl...",NKVD (Narodnıy komissariyat vnutrennnih del) (...,0,3,"[1973, 3027, 3095]",0
3,0fb1e793-3744-4b29-ba49-cdec7fb66cd2,Blohin'in Stalin rejimi sırasında infazları ge...,"Vasili Blohin, Stalin rejimi sırasında infazla...",1973 yılında imzalanan 1978 yılında değiştiril...,0,6,"[825, 968, 1319, 1532, 2303, 2884]",4
4,764a2ff6-053e-49e1-8274-a5dee96f0392,Cengel Operasyonu'nun amacı neydi?,"Cengel Operasyonu, Soğuk Savaş sırasında İngil...",Waffenamt (WaA) Alman Ordusu Silah Ajansı idi....,0,3,"[1949, 2321, 3138]",2
...,...,...,...,...,...,...,...,...
5994,e01f0903-4e8a-4f0c-9e19-54abdf262f7b,Tahrik sistemlerinde kullanılan farklı hız kon...,"Üzgünüm, bu konuda sana yardımcı olamam. Başka...","Sucuk (Azerice: sucuk, Kazakça: Шұжық , Kırgı...",1,5,"[917, 1021, 1245, 1595, 1770]",-1
5995,02d45da4-47e8-4f52-8889-26b82705629c,Stabschef rütbesi SA içinde ne kadar etkiliydi...,Sorunuzu yanıtlamak için yeterli bilgiye sahip...,"Gıda Paketi, Uzun Menzilli Devriye veya ""LRP r...",1,3,"[260, 1218, 1783]",-1
5996,8d61d4d2-1718-46f6-9193-0c4d1063656d,Brief'in dijital pazarlamada önemi nedir?,"Maalesef, bu konuda sana yardımcı olamam. Yete...",Gayrinizami harp; düzenli ve büyük birlikler y...,1,5,"[2052, 2323, 2560, 2883, 3271]",-1
5997,222a9194-9fbf-4400-9a9d-dc9515d231a2,"Hardy kivi diğer isimleriyle biliniyor, bu isi...",Bu soruyu cevaplamak için yeterli bilgiye sahi...,Kendi aralarında kendilerine Scene diyen alt k...,1,3,"[283, 617, 1031]",-1
5998,778997ef-a2dd-4b58-83ef-e04d6fdad181,AIL Storm'un hangi ülkeler tarafından kullanıl...,Bu soruyu cevaplamak için yeterli bilgiye sahi...,"Markov Zincirli Monte Carlo (MZMC) yöntem, den...",1,4,"[372, 764, 949, 1246]",-1

In [ ]:
'''
the function check the dataset and take questions
that have 5 or more answers 1 true 4 wrong
for questions that have more than 5 chunk it take
1 right 4 wrong
'''
# process chunks for each question
def process_chunks(row):
    chunks = []
    # parse ctx_split_points
    ctx_split_points = [0] + json.loads(row["ctx_split_points"])

    # generate all chunks
    for i in range(len(ctx_split_points) - 1):
        start, end = ctx_split_points[i], ctx_split_points[i + 1]
        chunk = row["context"][start:end]
        chunks.append((row["id"], row["question"], chunk, i == row["correct_intro_idx"]))

    # separate correct and incorrect chunks
    correct_chunks = [chunk for chunk in chunks if chunk[3]]  # correct
    incorrect_chunks = [chunk for chunk in chunks if not chunk[3]]  # incorrect

    # include questions with 5 or more chunks
    if len(chunks) >= 5:
        if len(chunks) == 5:
            # Ensure there's exactly 1 correct chunk
            if len(correct_chunks) == 1:
                return chunks
        elif len(chunks) > 5:
            # take 1 correct and 4 random incorrect chunks
            if len(correct_chunks) >= 1 and len(incorrect_chunks) >= 4:
                selected_chunks = correct_chunks[:1] + random.sample(incorrect_chunks, 4)
                return selected_chunks
    return []

In [ ]:
# process and collect valid chunks
all_chunks = []
for _, row in data.iterrows():
    valid_chunks = process_chunks(row)
    if valid_chunks:
        all_chunks.append(valid_chunks)

# flatten the list of chunks and create dataframe
flat_chunks = [chunk for question_chunks in all_chunks for chunk in question_chunks]
chunks_df = pd.DataFrame(flat_chunks, columns=["id", "question", "chunk", "is_correct"])

In [ ]:
# select 1000 questions
valid_question_ids = chunks_df["id"].unique()[:100]
final_chunks_df = chunks_df[chunks_df["id"].isin(valid_question_ids)].reset_index(drop=True)
final_chunks_df

,id,question,chunk,is_correct
0,fdb9e733-8b3f-430e-93d4-72c563f2d00c,Bermuda Adaları'nın Birleşik Krallık'a bağlı b...,"Bermuda, tam adıyla Bermuda Adaları (diğer adı...",True
1,fdb9e733-8b3f-430e-93d4-72c563f2d00c,Bermuda Adaları'nın Birleşik Krallık'a bağlı b...,TARDIS (Time And Relative Dimension In Space) ...,False
2,fdb9e733-8b3f-430e-93d4-72c563f2d00c,Bermuda Adaları'nın Birleşik Krallık'a bağlı b...,"Ekonomi tarihi veya iktisat tarihi, geçmişte y...",False
3,fdb9e733-8b3f-430e-93d4-72c563f2d00c,Bermuda Adaları'nın Birleşik Krallık'a bağlı b...,"Yoshiwara (Japonca: 吉原), Japonya'da Edo'da bul...",False
4,fdb9e733-8b3f-430e-93d4-72c563f2d00c,Bermuda Adaları'nın Birleşik Krallık'a bağlı b...,"Thingspiel (çoğulu Thingspiele), 1930'larda sa...",False
...,...,...,...,...
495,c60f63c5-2ded-4efd-bbc3-a92c56d6a6d9,Jeosferde depolanan karbonun büyük çoğunluğu h...,"Edmund Veesenmayer (d. 12 Kasım 1904, Bad Kiss...",False
496,c60f63c5-2ded-4efd-bbc3-a92c56d6a6d9,Jeosferde depolanan karbonun büyük çoğunluğu h...,"Mutajen, biyolojide canlıların DNA ya da RNA g...",False
497,c60f63c5-2ded-4efd-bbc3-a92c56d6a6d9,Jeosferde depolanan karbonun büyük çoğunluğu h...,"Karbon döngüsünün jeolojik bölümü, küresel kar...",True
498,c60f63c5-2ded-4efd-bbc3-a92c56d6a6d9,Jeosferde depolanan karbonun büyük çoğunluğu h...,"Richard Robert Ernst (d. 14 Ağustos 1933, Wint...",False
499,c60f63c5-2ded-4efd-bbc3-a92c56d6a6d9,Jeosferde depolanan karbonun büyük çoğunluğu h...,"Tura – Türk, Çuvaş ve Altay inancında Tanrı, R...",False

## **2. Generate embedding using multilingual-e5-large-instruct**

In [ ]:
model_name = "intfloat/multilingual-e5-large-instruct"
#"jinaai/jina-embeddings-v3"

# load tokenizer and model
print("Loading model and tokenizer...")
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModel.from_pretrained(model_name)
print("Model and tokenizer loaded successfully!")

# move model to GPU if available
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)

Loading model and tokenizer...
Model and tokenizer loaded successfully!

In [ ]:
'''
The `generate_embeddings` function turns a list of text chunks into numeric vectors (embeddings)
using a tokenizer and e5 model. It processes the text in small groups (batches) to handle large
amounts of data easily. For each group, it prepares the text, sends it through the model, and
collects the output as embeddings.
'''
def generate_embeddings(chunks, tokenizer, model, batch_size=16):
    model.eval()
    embeddings = []
    num_batches = (len(chunks) + batch_size - 1) // batch_size

    with torch.no_grad():
        for i in tqdm(range(0, len(chunks), batch_size), desc="Embedding chunks in batches", total=num_batches):
            batch = chunks[i:i + batch_size]

            # tokenize the batch
            inputs = tokenizer(batch, padding=True, truncation=True, return_tensors="pt")

            # generate embeddings using the model
            outputs = model(**inputs)

            # use the last hidden state (or other layers, depending on model specifics)
            batch_embeddings = outputs.last_hidden_state[:, 0, :]
            embeddings.append(batch_embeddings)

    # concatenate all embeddings
    embeddings = torch.cat(embeddings, dim=0)
    return embeddings

In [ ]:
# extract chunks for embedding
chunks = final_chunks_df["chunk"].tolist()
print(f"Total chunks to embed: {len(chunks)}")

Total chunks to embed: 500

In [ ]:
print("Generating embeddings...")
chunk_embeddings = generate_embeddings(chunks, tokenizer, model)
print(f"Embeddings generated: {chunk_embeddings.shape}")

Generating embeddings...

Embedding chunks in batches: 100%|██████████| 32/32 [12:14<00:00, 22.97s/it]

Embeddings generated: torch.Size([500, 1024])

In [ ]:
# convert embeddings to numpy

chunk_embeddings_np = chunk_embeddings.cpu().numpy()

# create dataframe
embeddings_df = final_chunks_df.copy()
embeddings_df["embedding"] = list(chunk_embeddings_np)  # add embeddings as a column
embeddings_df
#embeddings_df.to_pickle("chunk_embeddings.pkl")
#print("Embeddings and metadata saved!")

,id,question,chunk,is_correct,embedding
0,fdb9e733-8b3f-430e-93d4-72c563f2d00c,Bermuda Adaları'nın Birleşik Krallık'a bağlı b...,"Bermuda, tam adıyla Bermuda Adaları (diğer adı...",True,"[0.88241446, 0.34341228, -0.8748609, -2.015724..."
1,fdb9e733-8b3f-430e-93d4-72c563f2d00c,Bermuda Adaları'nın Birleşik Krallık'a bağlı b...,TARDIS (Time And Relative Dimension In Space) ...,False,"[0.81970173, 0.27505437, 0.19318302, -1.467915..."
2,fdb9e733-8b3f-430e-93d4-72c563f2d00c,Bermuda Adaları'nın Birleşik Krallık'a bağlı b...,"Ekonomi tarihi veya iktisat tarihi, geçmişte y...",False,"[0.31600657, 0.086823106, -0.42481276, -1.1809..."
3,fdb9e733-8b3f-430e-93d4-72c563f2d00c,Bermuda Adaları'nın Birleşik Krallık'a bağlı b...,"Yoshiwara (Japonca: 吉原), Japonya'da Edo'da bul...",False,"[0.28770986, 0.35837758, -1.0205408, -1.440830..."
4,fdb9e733-8b3f-430e-93d4-72c563f2d00c,Bermuda Adaları'nın Birleşik Krallık'a bağlı b...,"Thingspiel (çoğulu Thingspiele), 1930'larda sa...",False,"[0.21150964, 0.9428407, -0.9870129, -0.7547478..."
...,...,...,...,...,...
495,c60f63c5-2ded-4efd-bbc3-a92c56d6a6d9,Jeosferde depolanan karbonun büyük çoğunluğu h...,"Edmund Veesenmayer (d. 12 Kasım 1904, Bad Kiss...",False,"[0.09107962, -0.026543343, 0.04337078, -1.3356..."
496,c60f63c5-2ded-4efd-bbc3-a92c56d6a6d9,Jeosferde depolanan karbonun büyük çoğunluğu h...,"Mutajen, biyolojide canlıların DNA ya da RNA g...",False,"[1.35147, 0.07230453, 0.6058244, -1.5606025, 0..."
497,c60f63c5-2ded-4efd-bbc3-a92c56d6a6d9,Jeosferde depolanan karbonun büyük çoğunluğu h...,"Karbon döngüsünün jeolojik bölümü, küresel kar...",True,"[0.8029852, -0.13503811, -0.7630328, -1.622635..."
498,c60f63c5-2ded-4efd-bbc3-a92c56d6a6d9,Jeosferde depolanan karbonun büyük çoğunluğu h...,"Richard Robert Ernst (d. 14 Ağustos 1933, Wint...",False,"[0.5393561, -0.08631764, 0.50687766, -2.102073..."
499,c60f63c5-2ded-4efd-bbc3-a92c56d6a6d9,Jeosferde depolanan karbonun büyük çoğunluğu h...,"Tura – Türk, Çuvaş ve Altay inancında Tanrı, R...",False,"[0.6994357, 0.6604456, -0.16085681, -0.6187197..."

In [ ]:
# convert embeddings to NumPy
embedding_dim = chunk_embeddings_np.shape[1]  # Get the dimension of embeddings
print(f"Embedding dimension: {embedding_dim}")

# initialize a FAISS index for L2 (Euclidean) distance
index = faiss.IndexFlatL2(embedding_dim)

# add embeddings to the FAISS index
print("Adding embeddings to FAISS index...")
index.add(chunk_embeddings_np)
print(f"FAISS index size: {index.ntotal}")

Embedding dimension: 1024
Adding embeddings to FAISS index...
FAISS index size: 500

In [ ]:
# Save FAISS index to disk
#faiss.write_index(index, "/content/drive/My Drive/Colab Notebooks/chunk_embeddings_index5k-e5.faiss")
#print("FAISS index saved to 'chunk_embeddings_index.faiss'.")
# Save metadata (e.g., questions, chunks, is_correct) to disk
#embeddings_df.to_csv("/content/drive/My Drive/Colab Notebooks/chunk_metadata5k-e5.csv", index=False)
#print("Metadata saved to 'chunk_metadata.csv'.")

## **3. Retrieval**

In [ ]:
'''
The `retrieve_similar_chunks` function finds the most relevant text chunks for a given query.
It first converts the query into an embedding using a tokenizer and model.
Then, it compares this query embedding with pre-stored embeddings in an index to find
the top `k` most similar chunks based on distance. Finally, it retrieves metadata
(like the chunk text) for these matches and returns them along with their similarity scores.
'''
def retrieve_similar_chunks(query, tokenizer, model, index, metadata_df, top_k=5):
    # tokenize and encode the query
    inputs = tokenizer(query, return_tensors="pt", truncation=True, padding=True)
    with torch.no_grad():
        query_embedding = model(**inputs).last_hidden_state.mean(dim=1).numpy()

    # search for top-k similar chunks, "distance metric"
    distances, indices = index.search(query_embedding, top_k)

    # retrieve corresponding metadata
    results = metadata_df.iloc[indices[0]]
    return results, distances[0]

In [ ]:
# test retrieval function
sample_query = "Bermuda Adaları hakkında bilgi verin."
results, distances = retrieve_similar_chunks(
    sample_query, tokenizer, model, index, embeddings_df, top_k=5)

print("Top-5 Retrieved Chunks:")
for i, (chunk, dist) in enumerate(zip(results["chunk"], distances)):
    print(f"{i + 1}. Distance: {dist:.4f}, Chunk: {chunk}")

Top-5 Retrieved Chunks:
1. Distance: 265.9328, Chunk: Sinop Tersanesi, Osmanlı İmparatorluğu'nun Karadeniz'deki ana tersanesi.

2. Distance: 295.1357, Chunk: Bermuda, tam adıyla Bermuda Adaları (diğer adıyla Somers Adaları), Atlas Okyanusu'nda, ABD'nin doğu (Kuzey Carolina eyaletindeki Hatteras Burnu'nun yaklaşık 900 km doğusunda) ve Karayipler'in kuzey açıklarında bir takımadadır. Birleşik Krallık'ın denizaşırı topraklarından biridir. Ana ada olan Bermuda adası dâhil yedi ana ada ile 150 küçük ada ve kayalıktan oluşur.
Toplam yüzölçümü 53,3 km²'dir. Başkenti Hamilton'dur, nüfus 65.000 civarındadır.

3. Distance: 297.3138, Chunk: Ford Prefect, Otostopçunun Galaksi Rehberi serisinin baş karakterlerinden biridir.

4. Distance: 301.1673, Chunk: Hidrotermal baca, jeotermal ısıya sahip suyun salındığı bir deniz tabağı yarığıdır.

5. Distance: 308.5385, Chunk: Hawaii dini, Yerli Hawaililerin yerli dini inançlarını ve uygulamalarını kapsar.

## **4. Retrieval evaluation**

In [ ]:
'''
The `evaluate_retrieval_with_samples` function assesses the performance of a retrieval system
by testing it on a dataset of questions and their corresponding correct chunks.
For each question, it retrieves the top `k` most similar chunks and checks if the correct chunk
appears as the top result (top-1) or within the top five results (top-5). The function tracks
the number of correct top-1 and top-5 results, storing examples of correct and incorrect retrievals.
At the end, it calculates the accuracy for both top-1 and top-5 results and returns these accuracy
metrics along with detailed samples of the retrieval outcomes.
'''
def evaluate_retrieval_with_samples(metadata_df, tokenizer, model, index, top_k=5):
    correct_top1 = 0
    correct_top5 = 0
    samples = {
        "top1_correct": [],
        "top1_incorrect": [],
        "top5_incorrect": [],
        "all_retrieved": [],  # store all retrievals for each query
    }

    for _, row in metadata_df.iterrows():
        query = row["question"]
        correct_chunk = row["chunk"]

        # retrieve results
        results, _ = retrieve_similar_chunks(query, tokenizer, model, index, metadata_df, top_k=top_k)
        retrieved_chunks = results["chunk"].tolist()

        # store all retrieved results for this query
        samples["all_retrieved"].append({
            "query": query,
            "retrieved_chunks": retrieved_chunks,
            "correct_chunk": correct_chunk,
        })

        # check if the correct chunk is in the top-1 or top-5
        is_top1_correct = correct_chunk == retrieved_chunks[0]
        is_top5_correct = correct_chunk in retrieved_chunks

        # update accuracies and samples
        if is_top1_correct:
            correct_top1 += 1
            samples["top1_correct"].append({
                "query": query,
                "retrieved_chunk": retrieved_chunks[0],
                "correct_chunk": correct_chunk,
            })
        else:
            samples["top1_incorrect"].append({
                "query": query,
                "retrieved_chunk": retrieved_chunks[0],
                "correct_chunk": correct_chunk,
            })

        if not is_top5_correct:
            samples["top5_incorrect"].append({
                "query": query,
                "retrieved_chunks": retrieved_chunks,
                "correct_chunk": correct_chunk,
            })

        if is_top5_correct:
            correct_top5 += 1

    # calculate accuracies
    total_questions = len(metadata_df)
    top1_accuracy = correct_top1 / total_questions
    top5_accuracy = correct_top5 / total_questions

    # convert samples to DataFrames
    samples_dfs = {key: pd.DataFrame(value) for key, value in samples.items()}

    return top1_accuracy, top5_accuracy, samples_dfs

In [ ]:
# evaluate retrieval and get results
top1_accuracy, top5_accuracy, samples = evaluate_retrieval_with_samples(
    metadata_df=embeddings_df,
    tokenizer=tokenizer,
    model=model,
    index=index,
    top_k=5)

print(f"Top-1 Accuracy: {top1_accuracy:.2%}")
print(f"Top-5 Accuracy: {top5_accuracy:.2%}")

Top-1 Accuracy: 7.20%
Top-5 Accuracy: 10.80%

In [ ]:
for key, df in samples.items():
    print(f"{key}: {df.shape}")

top1_correct: (36, 3)
top1_incorrect: (464, 3)
top5_incorrect: (446, 3)
all_retrieved: (500, 3)

In [ ]:
# Check if 'top1_incorrect' exists in samples_fine
#if "top1_incorrect" in samples:
 #   incorrect_top1_indices = samples["top1_incorrect"].index.tolist()
  #  print("Indices of Incorrect Top-1 Retrievals:")
   # print(incorrect_top1_indices)
#else:
 #   print("The 'top1_incorrect' category is missing in samples_fine.")

In [ ]:
"""
Display retrieval results for specific indices.
- samples_fine: The dictionary containing DataFrames for retrieval results.
- indices: List of specific indices to display.
"""
def display_specific_indices(samples_fine, indices):
    if "all_retrieved" not in samples_fine:
        print("The 'all_retrieved' category is missing in samples_fine.")
        return

    all_retrieved = samples_fine["all_retrieved"]

    # ensure indices are within bounds
    if max(indices) >= len(all_retrieved) or min(indices) < 0:
        print("Error: Some indices are out of range.")
        return

    print("Retrieval Results for Specific Indices:")
    print("=" * 80)

    for idx in indices:
        row = all_retrieved.iloc[idx]
        print(f"Query: {row['query']}")
        print(f"Correct Answer: {row['correct_chunk']}")
        print(f"Retrieved Top-1: {row['retrieved_chunks'][0]}")
        print("Retrieved Top-5:")
        for i, chunk in enumerate(row['retrieved_chunks'][:5], start=1):
            print(f"  {i}. {chunk}")
        print("-" * 80)

In [ ]:
specific_indices = [0, 44, 88]  # replace with the indices you're interested in
display_specific_indices(samples, specific_indices)

Retrieval Results for Specific Indices:
================================================================================
Query: Bermuda Adaları'nın Birleşik Krallık'a bağlı bir bölge olmasının tarihi sebepleri nelerdir?
Correct Answer: Bermuda, tam adıyla Bermuda Adaları (diğer adıyla Somers Adaları), Atlas Okyanusu'nda, ABD'nin doğu (Kuzey Carolina eyaletindeki Hatteras Burnu'nun yaklaşık 900 km doğusunda) ve Karayipler'in kuzey açıklarında bir takımadadır. Birleşik Krallık'ın denizaşırı topraklarından biridir. Ana ada olan Bermuda adası dâhil yedi ana ada ile 150 küçük ada ve kayalıktan oluşur.
Toplam yüzölçümü 53,3 km²'dir. Başkenti Hamilton'dur, nüfus 65.000 civarındadır.

Retrieved Top-1: Sinop Tersanesi, Osmanlı İmparatorluğu'nun Karadeniz'deki ana tersanesi.

Retrieved Top-5:
  1. Sinop Tersanesi, Osmanlı İmparatorluğu'nun Karadeniz'deki ana tersanesi.

  2. Ege Seferi, Kaptan-ı derya Hamza Bey komutasındaki Osmanlı donanmasının İstanbul'un Fethinden (1453) sonra Ege Denizi'nde hâkimiyetini yerleştirme hedefine yönelik seferlerinden ilki.

  3. Ege Seferi, Kaptan-ı derya Hamza Bey komutasındaki Osmanlı donanmasının İstanbul'un Fethinden (1453) sonra Ege Denizi'nde hâkimiyetini yerleştirme hedefine yönelik seferlerinden ilki.

  4. Ukash, Birleşik Krallık kökenli elektronik kart ve güvenlik şirketidir. 2005 yılında kurulan şirket 31 Ekim 2015 tarihinde kapanmıştır.
Ukash sisteminde ATM'de kullanıcıların şifre güvenliğini sağlama özelliği vardır.
  5. Ford Prefect, Otostopçunun Galaksi Rehberi serisinin baş karakterlerinden biridir.

--------------------------------------------------------------------------------
Query: Uranyum-Toryum yöntemi ile hangi tür malzemelerin yaşı tespit edilebilir?
Correct Answer: He Jiankui ([xɤ̂ tɕjɛ̂nkʰwěi]; Çince: 贺建奎; doğumu: 1984), Çinli biyofizikçidir. Çin'in Shenzhen şehrinde bulunan Güney Bilim ve Teknoloji Üniversitesinin Biyoloji bölümünde doçent olarak görev yapmıştır.
Retrieved Top-1: Sinop Tersanesi, Osmanlı İmparatorluğu'nun Karadeniz'deki ana tersanesi.

Retrieved Top-5:
  1. Sinop Tersanesi, Osmanlı İmparatorluğu'nun Karadeniz'deki ana tersanesi.

  2. Ford Prefect, Otostopçunun Galaksi Rehberi serisinin baş karakterlerinden biridir.

  3. Langmuir-Blodgett filmi, Langmuir filmlerinin sıvı-gaz interfazdan katı faza geçmesiyle meydana gelen nanoyapısal bir sistemdir.
  4. Nivelman, noktalar arasındaki yükseklik farkını belirlemek amacıyla doğrudan ya da dolaylı olarak düşey mesafeleri ölçme işlemleridir.

  5. Hiperpolarizasyon, ısıl denge koşullarının ötesindeki malzemelerde görülen spin polarizasyonudur. Hiperpolarize durumdaki soy gazlar, manyetik rezonans görüntülemede kullanılmaktadır.

--------------------------------------------------------------------------------
Query: Otomatik musluklar genellikle nasıl çalışır?
Correct Answer: 25 Scorpii, Akrep takımyıldızı yönünde yaklaşık olarak 690 ışık yılı uzaklıkta bulunan K-tipi turuncu bir parlak dev yıldızdır.
25 Scorpii, Gökada içinde Güneş'e göre 15,3 km/sn'lik bir hızla hareket eder. Gökada merkezinden uzaklığı, 21.200 ile 24.800 ışık yılı aralığında değişmektedir.

Retrieved Top-1: Otomatik musluk veya musluk (ayrıca eller serbest musluk, temassız musluk, elektronik musluk, hareket algılayıcı musluk, sensörlü musluk veya kızılötesi musluk) yakın çevredeki kullanıcının ellerinin varlığına tepki olarak suyun akmasına izin verip vanasını açan mekanizma ve yakınlık sensörüyle donatılmış bir musluktur. Musluk birkaç saniye sonra veya kullanıcının ellerinin varlığını artık algılamadığında valfini tekrar kapatır.
Çoğu otomatik musluk pille çalışır ve el hareketini algılamak için aktif bir kızılötesi sensör içerir.
Retrieved Top-5:
  1. Otomatik musluk veya musluk (ayrıca eller serbest musluk, temassız musluk, elektronik musluk, hareket algılayıcı musluk, sensörlü musluk veya kızılötesi musluk) yakın çevredeki kullanıcının ellerinin varlığına tepki olarak suyun akmasına izin verip vanasını açan mekanizma ve yakınlık sensörüyle donatılmış bir musluktur. Musluk birkaç saniye sonra veya kullanıcının ellerinin varlığını artık algılamadığında valfini tekrar kapatır.
Çoğu otomatik musluk pille çalışır ve el hareketini algılamak için aktif bir kızılötesi sensör içerir.
  2. Ford Prefect, Otostopçunun Galaksi Rehberi serisinin baş karakterlerinden biridir.

  3. Sinop Tersanesi, Osmanlı İmparatorluğu'nun Karadeniz'deki ana tersanesi.

  4. Otomotiv mühendisliği'nde multi-supap veya multisupap motor, her bir silindir ikiden fazla supapın olmasıdır. Çok supaplı motor daha iyi nefes alır ve iki valfli bir motordan daha yüksek devir/dakika (RPM) ile çalışarak daha fazla güç verebilir.

  5. El kurutma makinesi, elleri yıkadıktan sonra elleri kurutmak için bir ısıtma elemanı ve bir hava üfleyiciden yararlanabilen elektrikli bir makinedir. Kağıt havlulara uygun maliyetli bir alternatif olarak umumi tuvaletlerde yaygın olarak kullanılır.
Bir düğmeye basarak veya otomatik olarak bir sensör kullanarak çalışabilir.

--------------------------------------------------------------------------------

## **5. Creating classifier**

* **Prepare the Dataset**: Create a copy of the DataFrame, convert the `is_correct` column to labels, and split the data into training (80%) and validation (20%) sets.

* **Tokenize Texts**: Define a function to tokenize the text data with truncation and padding, then apply it to the training and validation sets.

* **Create PyTorch Datasets**: Define a custom dataset class to handle the encodings and labels, and initialize training and validation datasets.

* **Initialize the Model**: Load a pretrained sequence classification model and transfer it to the appropriate device.

* **Define Metrics Function**: Set up an accuracy metric and create a function to compute it from predictions and labels.

* **Set Up the Trainer**: Specify training arguments (like output directory, evaluation strategy, and batch sizes) and create a trainer instance with the model and datasets.

* **Train the Model**: Call the `train` method to fine-tune the model on the training dataset.

* **Save the Model**: After training, save the fine-tuned model and tokenizer to a specified directory, and print a completion message.

In [ ]:
# prepare the dataset for fine-tuning
fine_tune_data = final_chunks_df.copy()
fine_tune_data["label"] = fine_tune_data["is_correct"].astype(int)

# split into training and validation sets
train_texts, val_texts, train_labels, val_labels = train_test_split(
    fine_tune_data["chunk"].tolist(),
    fine_tune_data["label"].tolist(),
    test_size=0.2,
    random_state=42
)

# tokenize the dataset
def tokenize_function(texts):
    return tokenizer(texts, truncation=True, padding=True, max_length=128)

train_encodings = tokenize_function(train_texts)
val_encodings = tokenize_function(val_texts)

# convert to PyTorch datasets
class RetrievalDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item["labels"] = torch.tensor(self.labels[idx])
        return item

train_dataset = RetrievalDataset(train_encodings, train_labels)
val_dataset = RetrievalDataset(val_encodings, val_labels)

In [ ]:
#train_dataset

In [ ]:
# initialize the model for fine-tuning
fine_tune_model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=2)
fine_tune_model.to(device)

# define compute metrics function
metric = load("accuracy")

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = torch.argmax(torch.tensor(logits), axis=1)
    accuracy = (predictions == labels).float().mean().item()
    return {"accuracy": accuracy}

# set up Trainer
training_args = TrainingArguments(
    output_dir="./results",
    eval_strategy="epoch",
    save_strategy="epoch",
    logging_dir="./logs",
    logging_steps=5,
    report_to="tensorboard",
    learning_rate=5e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=5,
    weight_decay=0.01,
    save_total_limit=2,
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss"
)

trainer = Trainer(
    model=fine_tune_model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    compute_metrics=compute_metrics,
)

# train the model
trainer.train()

# save the fine-tuned model
fine_tune_model.save_pretrained("./fine_tuned_model")
tokenizer.save_pretrained("./fine_tuned_model")
print("Fine-tuning complete and model saved!")

Some weights of XLMRobertaForSequenceClassification were not initialized from the model checkpoint at intfloat/multilingual-e5-large-instruct and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Fine-tuning complete and model saved!

## **5.1 Generate embeddings for classifier**

In [ ]:
def generate_fine_tuned_embeddings(chunks, tokenizer, model, batch_size=16):
    model.eval()
    embeddings = []
    num_batches = (len(chunks) + batch_size - 1) // batch_size

    with torch.no_grad():
        for i in tqdm(range(0, len(chunks), batch_size), desc="Generating fine-tuned embeddings", total=num_batches):
            batch = chunks[i:i + batch_size]
            inputs = tokenizer(batch, padding=True, truncation=True, return_tensors="pt").to(device)
            outputs = model(**inputs, output_hidden_states=True).hidden_states[-1]
            batch_embeddings = outputs.mean(dim=1)
            embeddings.append(batch_embeddings)

    embeddings = torch.cat(embeddings, dim=0)
    return embeddings

fine_tuned_embeddings = generate_fine_tuned_embeddings(fine_tune_data["chunk"].tolist(), tokenizer, fine_tune_model)
fine_tuned_embeddings_np = fine_tuned_embeddings.cpu().numpy()

Generating fine-tuned embeddings: 100%|██████████| 32/32 [10:32<00:00, 19.76s/it]

## **5.2. Retrieval an evaluation**

In [ ]:
# define retrieval and evaluation functions
def retrieve_with_classifier(query, chunks_df, tokenizer, model, top_k=5):
    scores = []
    for _, row in chunks_df.iterrows():
        question, chunk = row["question"], row["chunk"]
        inputs = tokenizer(question, chunk, return_tensors="pt", truncation=True, padding=True, max_length=512).to(device)
        with torch.no_grad():
            logits = model(**inputs).logits
            score = torch.softmax(logits, dim=-1)[0][1].item()
            scores.append((chunk, score))
    scores = sorted(scores, key=lambda x: x[1], reverse=True)
    return scores[:top_k]

def evaluate_classifier(chunks_df, tokenizer, model, top_k=5):
    correct_top1 = 0
    correct_top5 = 0
    samples = {"top1_correct": [], "top1_incorrect": [], "top5_incorrect": [], "all_retrieved": []}

    for question_id in chunks_df["id"].unique():
        question_df = chunks_df[chunks_df["id"] == question_id]
        query = question_df.iloc[0]["question"]
        correct_chunk = question_df[question_df["is_correct"] == 1]["chunk"].iloc[0]
        retrieved_chunks = retrieve_with_classifier(query, question_df, tokenizer, model, top_k=top_k)
        samples["all_retrieved"].append({
            "query": query,
            "retrieved_chunks": [chunk for chunk, _ in retrieved_chunks],
            "retrieved_scores": [score for _, score in retrieved_chunks],
            "correct_chunk": correct_chunk,
        })
        is_top1_correct = correct_chunk == retrieved_chunks[0][0]
        is_top5_correct = correct_chunk in [chunk for chunk, _ in retrieved_chunks]

        if is_top1_correct:
            correct_top1 += 1
            samples["top1_correct"].append({"query": query, "retrieved_chunk": retrieved_chunks[0][0], "correct_chunk": correct_chunk})
        else:
            samples["top1_incorrect"].append({"query": query, "retrieved_chunk": retrieved_chunks[0][0], "correct_chunk": correct_chunk})

        if not is_top5_correct:
            samples["top5_incorrect"].append({"query": query, "retrieved_chunks": [chunk for chunk, _ in retrieved_chunks], "correct_chunk": correct_chunk})
        if is_top5_correct:
            correct_top5 += 1

    total_questions = chunks_df["id"].nunique()
    top1_accuracy = correct_top1 / total_questions
    top5_accuracy = correct_top5 / total_questions
    samples_dfs = {key: pd.DataFrame(value) for key, value in samples.items()}
    return top1_accuracy, top5_accuracy, samples_dfs

# evaluate the fine-tuned model
#classifier_top1, classifier_top5, samples_fine = evaluate_classifier(chunks_df=fine_tune_data, tokenizer=tokenizer, model=fine_tune_model)
#print(f"Classifier Top-1 Accuracy: {classifier_top1:.2%}")
#print(f"Classifier Top-5 Accuracy: {classifier_top5:.2%}")

In [ ]:
"""
Display retrieval results for specific queries or the first 'limit' queries.
- queries: List of specific queries to display. If None, display the first 'limit' queries.S
- limit: Number of queries to display (only used if queries is None).
"""
def display_retrieval_results(samples_fine, queries=None, limit=5):
    if "all_retrieved" not in samples_fine:
        print("The 'all_retrieved' category is missing in samples_fine.")
        return

    print("Retrieval Results:")
    print("=" * 80)
    all_retrieved = samples_fine["all_retrieved"]

    # filter rows based on specific queries if provided
    if queries:
        filtered_rows = all_retrieved[all_retrieved['query'].isin(queries)]
    else:
        filtered_rows = all_retrieved.head(limit)

    if filtered_rows.empty:
        print("No matching queries found.")
        return

    # display results
    for _, row in filtered_rows.iterrows():
        print(f"Query: {row['query']}")
        print(f"Correct Answer: {row['correct_chunk']}")
        print(f"Retrieved Top-1: {row['retrieved_chunks'][0]}")
        print("Retrieved Top-5:")
        for i, chunk in enumerate(row['retrieved_chunks'][:5], start=1):
            print(f"  {i}. {chunk}")
        print("-" * 80)

In [ ]:
specific_indices = [0, 44,88]
display_retrieval_results(samples_fine, queries=samples_fine["all_retrieved"].iloc[specific_indices]["query"].tolist())

Retrieval Results:
================================================================================
Query: Bermuda Adaları'nın Birleşik Krallık'a bağlı bir bölge olmasının tarihi sebepleri nelerdir?
Correct Answer: Bermuda, tam adıyla Bermuda Adaları (diğer adıyla Somers Adaları), Atlas Okyanusu'nda, ABD'nin doğu (Kuzey Carolina eyaletindeki Hatteras Burnu'nun yaklaşık 900 km doğusunda) ve Karayipler'in kuzey açıklarında bir takımadadır. Birleşik Krallık'ın denizaşırı topraklarından biridir. Ana ada olan Bermuda adası dâhil yedi ana ada ile 150 küçük ada ve kayalıktan oluşur.
Toplam yüzölçümü 53,3 km²'dir. Başkenti Hamilton'dur, nüfus 65.000 civarındadır.

Retrieved Top-1: TARDIS (Time And Relative Dimension In Space) (Türkçe: Uzaydaki zaman ve izafi boyut), İngiliz bilimkurgu dizisi Doctor Who'daki uzay ve zamanda herhangi bir yere gidebilen, Gallifrey adlı bir gezegende yaşayan Zaman Lordları tarafından yaratılan bir zaman makinesidir. Bazen adı "The Blue Box" yani "Mavi Kulübe" olarak da geçer.
Asıl şekli olmasa da dışarıdan 1963 yılı Londrasından kalma bir polis telefon kulübesi olarak görünmektedir. Şekil değiştirmesini sağlayan kamuflaj ünitesi bozulduktan sonra Doktor onu tamir etmemiş, öyle bırakmıştır. Aynı anda 6 kişinin kullanabilme kapasitesi olan bu zaman makinesinin aynı zamanda içi dışından daha büyüktür. TARDIS'in içinde uyuma bölümleri, özel ihtiyaç odaları, gardırop, kütüphane, havuz, inziva odası ve kontrol odası bulunuyor. TARDIS içini kontrol edebilir, yeni odalar ekleyebilir ve bazı odaları silebilir. TARDIS, taşıdığı yolculara farklı dilleri anlama ve konuşma yetisi veren bir sisteme sahiptir. Ayrıca her TARDIS'in kendine has bir zekası ve kişiliği vardır.
Doktor onu çalmıştır ya da kendi söylediğine göre ödünç almıştır ve onunla birlikte son büyük zaman savaşından kaçmayı başarmıştır. "The Doctor's Wife" bölümünde TARDIS insan görünümündedir ve Doktor'un kendisini çaldığını değil de kendisinin Doktor'u çaldığını iddia eder.
Doctor Who dizisi İngiltere'nin her yerine yayıldıktan sonra popüler kültür arasına girmeyi de başarmıştır. "TARDIS" kelimesi artık içi dışından büyük görünen herhangi bir şeyin adı olmuştur.
Kavramsal tarihi 1963'te Doctor Who dizisi yazılırken, yazan kişiler Doktor'un zaman makinesinin neye benzemesi gerektiğini tartışmaktaydılar. Belli bir şekilde tutmak için "Police Box" olarak yapılmasına karar verilmişti. Ve the ship's "chameleon circuit" adlı bölümde şeklinin aynı olmasının nedeni açıklanmıştı.
Diğer Zaman Lordları TARDIS'in bir diğer adı olan TT Kapsülü yani Time Travel Capsule (Zaman Yolculuğu Kapsülü) adını kullanmaktadırlar.

Retrieved Top-5:
  1. TARDIS (Time And Relative Dimension In Space) (Türkçe: Uzaydaki zaman ve izafi boyut), İngiliz bilimkurgu dizisi Doctor Who'daki uzay ve zamanda herhangi bir yere gidebilen, Gallifrey adlı bir gezegende yaşayan Zaman Lordları tarafından yaratılan bir zaman makinesidir. Bazen adı "The Blue Box" yani "Mavi Kulübe" olarak da geçer.
Asıl şekli olmasa da dışarıdan 1963 yılı Londrasından kalma bir polis telefon kulübesi olarak görünmektedir. Şekil değiştirmesini sağlayan kamuflaj ünitesi bozulduktan sonra Doktor onu tamir etmemiş, öyle bırakmıştır. Aynı anda 6 kişinin kullanabilme kapasitesi olan bu zaman makinesinin aynı zamanda içi dışından daha büyüktür. TARDIS'in içinde uyuma bölümleri, özel ihtiyaç odaları, gardırop, kütüphane, havuz, inziva odası ve kontrol odası bulunuyor. TARDIS içini kontrol edebilir, yeni odalar ekleyebilir ve bazı odaları silebilir. TARDIS, taşıdığı yolculara farklı dilleri anlama ve konuşma yetisi veren bir sisteme sahiptir. Ayrıca her TARDIS'in kendine has bir zekası ve kişiliği vardır.
Doktor onu çalmıştır ya da kendi söylediğine göre ödünç almıştır ve onunla birlikte son büyük zaman savaşından kaçmayı başarmıştır. "The Doctor's Wife" bölümünde TARDIS insan görünümündedir ve Doktor'un kendisini çaldığını değil de kendisinin Doktor'u çaldığını iddia eder.
Doctor Who dizisi İngiltere'nin her yerine yayıldıktan sonra popüler kültür arasına girmeyi de başarmıştır. "TARDIS" kelimesi artık içi dışından büyük görünen herhangi bir şeyin adı olmuştur.
Kavramsal tarihi 1963'te Doctor Who dizisi yazılırken, yazan kişiler Doktor'un zaman makinesinin neye benzemesi gerektiğini tartışmaktaydılar. Belli bir şekilde tutmak için "Police Box" olarak yapılmasına karar verilmişti. Ve the ship's "chameleon circuit" adlı bölümde şeklinin aynı olmasının nedeni açıklanmıştı.
Diğer Zaman Lordları TARDIS'in bir diğer adı olan TT Kapsülü yani Time Travel Capsule (Zaman Yolculuğu Kapsülü) adını kullanmaktadırlar.

  2. American Horror Story: Asylum (Türkçesi: Amerikan Korku Hikayesi: Akıl Hastanesi), FX tarafından yayınlanan korku-gerilim dizisi American Horror Story'nin ikinci sezonudur. 17 Ekim 2012 - 23 Ocak 2013 tarihleri arasında yayınlanmıştır. İkinci sezonda konu gidişatı ve karakterler ilk sezondan bağımsız olduğu için, dizi American Horror Story başlığı altında bir antoloji serisi olmuştur.
Sezon, 1964 yılında kurgusal bir akıl hastanesi olan Briarcliff Hastanesi'ndeki hastaların, görevlilerin geçmişteki ve gelecekteki hallerini işler. İlk sezondaki karakterlerden Frances Conroy, Jessica Lange, Dylan McDermott, Sarah Paulson, Evan Peters, Zachary Quinto ve Lily Rabe bu sezonda ana karakterleri canlandırmaktadır.
İlk sezon gibi Asylum da eleştirmenlerden ve hayranlardan olumlu eleştiriler aldı. Jessica Lange'in, James Cromwell'in, Zachary Quinto'nun, Sarah Paulson'un ve Lily Rabe'in oyunculukları yer yer çok övüldü. İkinci sezon, Emmy Ödüllerinden toplamda 17 ödül kazandı. Ödüller arasında En İyi TV Dizisi Performansları ve Jessica Lange'in, Sarah Paulson'un, James Cromwell'in ve Zachary Quinto'nun oyunculuk dalında aday oldukları dallarda Cromwell, En İyi Dizi veya Film dalındaki En İyi Yardımcı Oyuncu ödülünü aldı. 3. Eleştirmenlerin Seçimi Televizyon Ödüllerinde ise Quinto ve Paulson, Yardımcı Oyuncu ödüllerini aldılar.
Antoloji serisi olması dışında Lily Rabe, Naomi Grossman ve John Cromwell gibi bazı kadro oyuncularının, dizinin dördüncü sezonu American Horror Story: Freak Show'daki karakterlerle bağlantısı da vardır.

  3. Thingspiel (çoğulu Thingspiele), 1930'larda savaş öncesi Nazi Almanyası'nda kısa süreli popülerlik kazanmış çok disiplinli bir açık hava tiyatrosu performansıydı. Thingplatz veya Thingstätte, bu tür performanslar için özel olarak inşa edilmiş bir açık hava amfitiyatrosuydu. Yaklaşık 400 adet planlanmıştı, ancak 1933 ile 1939 yılları arasında sadece 40 tanesi inşa edildi.

  4. Yoshiwara (Japonca: 吉原), Japonya'da Edo'da bulunan bir yūkaku idi. 1617'de kurulmuş olup Tokugawa şogunluğu tarafından 17. yüzyılın başlarında, Kyoto'daki Shimabara ve Osaka'daki Shinmachi'nin yanı sıra 17. yüzyılın başlarında kurulan üç lisanslı ve tanınmış kırmızı fener mahallesinden biriydi.
Şogunluk tarafından, yeni zengin chōnin (tüccar) sınıflarının zevklerini azaltmak ve tecrit etmek için yaratılan, Yoshiwara'da sunulan eğlence, diğer lisanslı bölgelerin yanı sıra, sonunda, moda yoldaşları olarak tanınacak geyşaların ortaya çıkardı. Chōnin sınıfları ve aynı zamanda kırmızı ışıklı bölgelerin üst sınıf nezaketçileri olan oiranların azalmasına neden oldu.
  5. Bermuda, tam adıyla Bermuda Adaları (diğer adıyla Somers Adaları), Atlas Okyanusu'nda, ABD'nin doğu (Kuzey Carolina eyaletindeki Hatteras Burnu'nun yaklaşık 900 km doğusunda) ve Karayipler'in kuzey açıklarında bir takımadadır. Birleşik Krallık'ın denizaşırı topraklarından biridir. Ana ada olan Bermuda adası dâhil yedi ana ada ile 150 küçük ada ve kayalıktan oluşur.
Toplam yüzölçümü 53,3 km²'dir. Başkenti Hamilton'dur, nüfus 65.000 civarındadır.

--------------------------------------------------------------------------------
Query: Su kalitesi değerlendirmesinde hangi standartlar en yaygın olarak kullanılır ve neden?
Correct Answer: Su kalitesi, suyun kimyasal, fiziksel, biyolojik ve radyolojik özelliklerini ifade eder. Bir veya daha fazla biyotik türün gereksinimlerine veya herhangi bir insan ihtiyacına veya amacına göre su durumunun bir ölçüsüdür. En sık olarak, genellikle suyun arıtılmasıyla elde edilen uygunluğun değerlendirilebileceği bir dizi standart referans alınarak kullanılır. Su kalitesini değerlendirmek için kullanılan en yaygın standartlar ekosistemlerin sağlığı, insan temasının güvenliği ve içme suyu ile ilgilidir.

Retrieved Top-1: Su kalitesi, suyun kimyasal, fiziksel, biyolojik ve radyolojik özelliklerini ifade eder. Bir veya daha fazla biyotik türün gereksinimlerine veya herhangi bir insan ihtiyacına veya amacına göre su durumunun bir ölçüsüdür. En sık olarak, genellikle suyun arıtılmasıyla elde edilen uygunluğun değerlendirilebileceği bir dizi standart referans alınarak kullanılır. Su kalitesini değerlendirmek için kullanılan en yaygın standartlar ekosistemlerin sağlığı, insan temasının güvenliği ve içme suyu ile ilgilidir.

Retrieved Top-5:
  1. Su kalitesi, suyun kimyasal, fiziksel, biyolojik ve radyolojik özelliklerini ifade eder. Bir veya daha fazla biyotik türün gereksinimlerine veya herhangi bir insan ihtiyacına veya amacına göre su durumunun bir ölçüsüdür. En sık olarak, genellikle suyun arıtılmasıyla elde edilen uygunluğun değerlendirilebileceği bir dizi standart referans alınarak kullanılır. Su kalitesini değerlendirmek için kullanılan en yaygın standartlar ekosistemlerin sağlığı, insan temasının güvenliği ve içme suyu ile ilgilidir.

  2. Serbest elektron lazeri, lazer ortamı, manyetik bir yapı boyunca serbestçe hareket eden çok hızlı elektronlar içeren bir tür lazerdir. Ayarlanabilir olan ve tüm lazer türleri arasında en geniş frekans aralığına sahip olan serbest elektron lazerleri; mikrodalgalardan, terahertz radyasyonu ile kızılötesine ve görünür spektrum, morötesi ve X ışınlarına kadar uzanan dalga boyuna sahiptir.

  3. Eski Mezopotamya dininde, Lugal-irra ve Meslamta-ea, Kuzey Babil'de bulunan Kisiga köyünde tapılan ikiz tanrılardır.  Kapıların koruyucuları olarak kabul edildiler  ve başlangıçta Yeraltı Dünyası'nın kapılarını koruyan bir dizi ikiz olarak tasfir edilmiş olabilirler.  Neo-Asur döneminde, küçük tasvirleri girişlere gömülürdü,  Lugal-irra her zaman solda ve Meslamta-ea her zaman sağda resmedilirdi.  Birebir aynılardır ve boynuzlu başlıklar takmış olarak gösterilirler. İkisi de bir balta ve bir gürz tutar.  Kendilerinden sonra adlandırılan İkizler takımyıldızı ile tanımlanırlar.

  4. Heinrich Eberbach (24 Kasım 1895 - 13 Temmuz 1992), II. Dünya Savaşı sırasında Nazi Almanyası'nın generali (General der Panzertruppe).

  5. UGC 717 veya Arp 11, Balıklar takımyıldızı yönünde yaklaşık olarak 495,75 MIy (152 Mpc)uzaklıkta bulunan bir çubuklu sarmal galaksidir. Galaksi içinde 20 Kasım 2009 tarihinde Tip IIP süpernova SN 2009lo keşfedilmiştir.
--------------------------------------------------------------------------------
Query: Kedi tuvalet kutularının temizliğinin önemi nedir ve kokuyu engellemek için neler yapılabilir?
Correct Answer: Bazen kum havuzu, kedi tuvalet kutusu veya kedi tuvaleti denilen kap kedilerin yanı sıra tavşanlar, yaban gelincik'ler, minyatür domuz'lar, küçük köpek'ler ve içgüdüsel olarak veya eğitim yoluyla böyle bir yerden yararlanan diğer evcil'ler için bir iç mekan dışkı ve idrar toplama kutusudur. Bir evde serbest dolaşımına izin verilen ancak metabolik atık için dışarı çıkamayan veya her zaman dışarı çıkmayan evcil hayvanlar için kullanılır. Bu hayvanların sahipleri, açık havadaki tehlikelere maruz kalma korkusuyla hayvanlarının dışarıda dolaşmalarına izin vermemeyi tercih eder. Ortalama, kapalı kedilerin ömrü 16.8 yıl iken, açık hava kedilerinin ömrü çok daha kısa, sadece 5.6 yıldır. Bu açık hava tehlikeleri arasında kötü hava durumu, yabani yaşam, trafik veya kedi immün yetmezlik virüsü gibi hastalıklar yer alır.
Vahşi doğada kediler, kolay gömmek için doğal olarak yumuşak veya kumlu toprağa dışkılarlar. Dışkılarını örtmek için patilerini geriye doğru süpürme hareketiyle kullanırlar. Bu içgüdüsel arzuyu harekete geçirmek için, kedi tuvalet kutusunun dibi genellikle 2 inç (5 cm) veya daha az kedi kumu ile doldurulur. Tuvalet kutusu dolgu maddesi, amonyak gibi nemi ve kokuları emen gevşek, tanecikli bir malzemedir. Bazı kum markaları, bu tür kokuları emmek için kabartma tozu içerir veya sahipleri, kutunun altında kedi kumunun altına, ince bir tabaka serpebilir. Altlık malzemesi ayrıca bir kedinin atıklarını gömmelerine izin vererek kokularını gizleme konusundaki içgüdüsel arzusunu da tatmin eder. En yaygın malzeme kildir, ancak geri dönüştürülmüş kâğıt "peletler" ve silika bazlı "kristal" çeşitleri de kullanılır. Bazen, sahibi kedinin doğal içgüdülerini harekete geçirmek istediğinde, doğal kir kullanılır.
Pisliğin içine döküldüğü kedi tuvalet kutusu, uygun şekilde temizlenmediğinde pis bir koku yayar. Tuvalet kutusundan kaçınmayı önlemek için, tuvalet kutusunun bodrum katı veya çamaşır odası gibi evin trafiğin az olduğu alanlarda tutulması tavsiye edilir. Çıkan kokuyu örtmeye veya azaltmaya yardımcı olmak için ticari olarak temin edilebilen özel tuvalet malzeme türleri vardır. Bunlar kabartma tozu, bitki özleri ve/veya kokulu kristaller içerirler. Hava girişi olan bir odada tutulursa, kokuyu evin geri kalanından izole etmek için fırın filtresine oda spreyi eklenebilir.

Retrieved Top-1: Sicim teorisi, parçacık fiziğinde, kuantum mekaniği ile Einstein'in genel görelilik kuramını birleştiren bir teori. "Sicim" adı, klasik yaklaşımda "sıfır boyutlu noktalar" şeklinde tarif edilen atomaltı parçacıkların, aslında "bir boyutlu ve ipliksi varlıklar" olabileceği varsayımına dayanır.
Sicim kuramı, belirli bir biçimde titreşen ipliksilerin, kütle ve yük gibi özelliklere sahip parçacıklar gibi davranabileceğini söyler. 1980'lerde fizikçiler, sicim kuramının doğadaki başlıca dört güç (kütleçekimi, elektromanyetizma, güçlü etkileşim [kuvvetli nükleer güç] ve zayıf etkileşim [zayıf nükleer güç]) ile maddenin tüm türlerini bir kuantum mekanik modelinde (uzun süredir beklenen "birleşik alan teorisi") birleştirme potansiyeline sahip olduğunu fark ettiler.
Sicim kuramı hızla gelişen ve üzerinde çok çalışılan bir alan olmakla birlikte, henüz deneysel gözlemi mümkün olmamış, matematiksel bir modeldir.

Retrieved Top-5:
  1. Sicim teorisi, parçacık fiziğinde, kuantum mekaniği ile Einstein'in genel görelilik kuramını birleştiren bir teori. "Sicim" adı, klasik yaklaşımda "sıfır boyutlu noktalar" şeklinde tarif edilen atomaltı parçacıkların, aslında "bir boyutlu ve ipliksi varlıklar" olabileceği varsayımına dayanır.
Sicim kuramı, belirli bir biçimde titreşen ipliksilerin, kütle ve yük gibi özelliklere sahip parçacıklar gibi davranabileceğini söyler. 1980'lerde fizikçiler, sicim kuramının doğadaki başlıca dört güç (kütleçekimi, elektromanyetizma, güçlü etkileşim [kuvvetli nükleer güç] ve zayıf etkileşim [zayıf nükleer güç]) ile maddenin tüm türlerini bir kuantum mekanik modelinde (uzun süredir beklenen "birleşik alan teorisi") birleştirme potansiyeline sahip olduğunu fark ettiler.
Sicim kuramı hızla gelişen ve üzerinde çok çalışılan bir alan olmakla birlikte, henüz deneysel gözlemi mümkün olmamış, matematiksel bir modeldir.

  2. Bazen kum havuzu, kedi tuvalet kutusu veya kedi tuvaleti denilen kap kedilerin yanı sıra tavşanlar, yaban gelincik'ler, minyatür domuz'lar, küçük köpek'ler ve içgüdüsel olarak veya eğitim yoluyla böyle bir yerden yararlanan diğer evcil'ler için bir iç mekan dışkı ve idrar toplama kutusudur. Bir evde serbest dolaşımına izin verilen ancak metabolik atık için dışarı çıkamayan veya her zaman dışarı çıkmayan evcil hayvanlar için kullanılır. Bu hayvanların sahipleri, açık havadaki tehlikelere maruz kalma korkusuyla hayvanlarının dışarıda dolaşmalarına izin vermemeyi tercih eder. Ortalama, kapalı kedilerin ömrü 16.8 yıl iken, açık hava kedilerinin ömrü çok daha kısa, sadece 5.6 yıldır. Bu açık hava tehlikeleri arasında kötü hava durumu, yabani yaşam, trafik veya kedi immün yetmezlik virüsü gibi hastalıklar yer alır.
Vahşi doğada kediler, kolay gömmek için doğal olarak yumuşak veya kumlu toprağa dışkılarlar. Dışkılarını örtmek için patilerini geriye doğru süpürme hareketiyle kullanırlar. Bu içgüdüsel arzuyu harekete geçirmek için, kedi tuvalet kutusunun dibi genellikle 2 inç (5 cm) veya daha az kedi kumu ile doldurulur. Tuvalet kutusu dolgu maddesi, amonyak gibi nemi ve kokuları emen gevşek, tanecikli bir malzemedir. Bazı kum markaları, bu tür kokuları emmek için kabartma tozu içerir veya sahipleri, kutunun altında kedi kumunun altına, ince bir tabaka serpebilir. Altlık malzemesi ayrıca bir kedinin atıklarını gömmelerine izin vererek kokularını gizleme konusundaki içgüdüsel arzusunu da tatmin eder. En yaygın malzeme kildir, ancak geri dönüştürülmüş kâğıt "peletler" ve silika bazlı "kristal" çeşitleri de kullanılır. Bazen, sahibi kedinin doğal içgüdülerini harekete geçirmek istediğinde, doğal kir kullanılır.
Pisliğin içine döküldüğü kedi tuvalet kutusu, uygun şekilde temizlenmediğinde pis bir koku yayar. Tuvalet kutusundan kaçınmayı önlemek için, tuvalet kutusunun bodrum katı veya çamaşır odası gibi evin trafiğin az olduğu alanlarda tutulması tavsiye edilir. Çıkan kokuyu örtmeye veya azaltmaya yardımcı olmak için ticari olarak temin edilebilen özel tuvalet malzeme türleri vardır. Bunlar kabartma tozu, bitki özleri ve/veya kokulu kristaller içerirler. Hava girişi olan bir odada tutulursa, kokuyu evin geri kalanından izole etmek için fırın filtresine oda spreyi eklenebilir.

  3. Carl Sagan Award for Public Understanding of Science, Council of Scientific Society Presidents tarafından verilen  halk tarafından tanınmış araştırmacı, bilim insanları, eğitimciler ve halka bilimi anlamasını sağlayan kişilere verilir. Ödül ilk olarak ödülle de onuruna aynı adı taşıyan Carl Sagan tarafından verildi.
  4. Ordnungspolizei (kısaca: OrPo veya Orpo, üniformasının renginden dolayı Grüne Polizei), Nazi Almanyası'nın normal polisi.
Nazi Almanyası döneminde özellikle 1936 - 1945 yılları arasında Sicherheitspolizei (SiPo) ile birlikte rejimi korumakta önemli rolü oynadı.
Milyonlarca Yahudi ve Sovyet savaş esiri Ordnungspolizei mensupları tarafından infaz edildi.

  5. Dilivium, bir jeoloji terimidir. Sel ve taşkın sularının yüzeysel akışı sırasında bünyesinde taşıdığı kil ve benzeri alüvyonları yavaş ve istikrarlı bir şekilde biriktirmesiyle oluşan kayaçlardır. Bu terim eskiden Nuh tufanının neden olduğu sanılan kaya kil katmanlarına verilirdi.
20. yüzyılın sonlarında Rus coğrafyacı Alexei Rudoy dilivium terimini Altay havzası dağlar asındaki Buzul Çağı dev buzul barajı göllerinin katastrofik patlamaları sonucu oluşan katmanların tanımı için önermiştir. Bu göllerin en genişleri, Chuya ve Kuray, yüzlerce kilometre su hacmine sahipti ve bunların zirve hidrografi akış hızındaki tahliye oranı, Kuzey Amerika’daki meşhur Pleistosen Lake Missoula selinin azami oranlarını aşmıştır.

--------------------------------------------------------------------------------

## **6. Classifier Fine Tuning**

In [ ]:
# prepare the dataset for fine-tuning
#fine_tune_data2 = final_chunks_df.copy()
#fine_tune_data2["label"] = fine_tune_data["is_correct"].astype(int)

# split into training and validation sets
#train_texts2, val_texts2, train_labels2, val_labels2 = train_test_split(
 #   fine_tune_data["chunk"].tolist(),
  #  fine_tune_data["label"].tolist(),
   #test_size=0.2,
    #random_state=42)

#train_encodings2 = tokenize_function(train_texts2)
#val_encodings2 = tokenize_function(val_texts2)

#train_dataset2 = RetrievalDataset(train_encodings2, train_labels2)
#val_dataset2 = RetrievalDataset(val_encodings2, val_labels2)

In [ ]:
# set up Trainer
training_args2 = TrainingArguments(
    output_dir="./results",
    eval_strategy="epoch",
    save_strategy="epoch",
    logging_dir="./logs",
    logging_steps=10,
    report_to="tensorboard",
    learning_rate=5e-5,
    per_device_train_batch_size=32,
    per_device_eval_batch_size=32,
    num_train_epochs=10,
    weight_decay=0.01,
    save_total_limit=2,
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss"
)

trainer2 = Trainer(
    model=fine_tune_model,
    args=training_args2,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    compute_metrics=compute_metrics,
)

# train the model
trainer2.train()

# save the fine-tuned model
fine_tune_model.save_pretrained("./fine_tuned_model2")
tokenizer.save_pretrained("./fine_tuned_model2")
print("Fine-tuning complete and model2 saved!")

Fine-tuning complete and model2 saved!

In [ ]:
#fine_tuned_embeddings2 = generate_fine_tuned_embeddings(fine_tune_data["chunk"].tolist(), tokenizer, fine_tune_model)
#fine_tuned_embeddings_np2 = fine_tuned_embeddings2.cpu().numpy()

In [ ]:
# evaluate the fine-tuned model
fine_top1, fine_top5, samples_fine2 = evaluate_classifier(fine_tune_data, tokenizer, fine_tune_model)
print(f"Classifier Top-1 Accuracy: {fine_top1:.2%}")
print(f"Classifier Top-5 Accuracy: {fine_top5:.2%}")

Classifier Top-1 Accuracy: 49.00%
Classifier Top-5 Accuracy: 100.00%

In [ ]:
specific_indices = [0, 44,88]
display_retrieval_results(samples_fine2, queries=samples_fine2["all_retrieved"].iloc[specific_indices]["query"].tolist())

Retrieval Results:
================================================================================
Query: Bermuda Adaları'nın Birleşik Krallık'a bağlı bir bölge olmasının tarihi sebepleri nelerdir?
Correct Answer: Bermuda, tam adıyla Bermuda Adaları (diğer adıyla Somers Adaları), Atlas Okyanusu'nda, ABD'nin doğu (Kuzey Carolina eyaletindeki Hatteras Burnu'nun yaklaşık 900 km doğusunda) ve Karayipler'in kuzey açıklarında bir takımadadır. Birleşik Krallık'ın denizaşırı topraklarından biridir. Ana ada olan Bermuda adası dâhil yedi ana ada ile 150 küçük ada ve kayalıktan oluşur.
Toplam yüzölçümü 53,3 km²'dir. Başkenti Hamilton'dur, nüfus 65.000 civarındadır.

Retrieved Top-1: American Horror Story: Asylum (Türkçesi: Amerikan Korku Hikayesi: Akıl Hastanesi), FX tarafından yayınlanan korku-gerilim dizisi American Horror Story'nin ikinci sezonudur. 17 Ekim 2012 - 23 Ocak 2013 tarihleri arasında yayınlanmıştır. İkinci sezonda konu gidişatı ve karakterler ilk sezondan bağımsız olduğu için, dizi American Horror Story başlığı altında bir antoloji serisi olmuştur.
Sezon, 1964 yılında kurgusal bir akıl hastanesi olan Briarcliff Hastanesi'ndeki hastaların, görevlilerin geçmişteki ve gelecekteki hallerini işler. İlk sezondaki karakterlerden Frances Conroy, Jessica Lange, Dylan McDermott, Sarah Paulson, Evan Peters, Zachary Quinto ve Lily Rabe bu sezonda ana karakterleri canlandırmaktadır.
İlk sezon gibi Asylum da eleştirmenlerden ve hayranlardan olumlu eleştiriler aldı. Jessica Lange'in, James Cromwell'in, Zachary Quinto'nun, Sarah Paulson'un ve Lily Rabe'in oyunculukları yer yer çok övüldü. İkinci sezon, Emmy Ödüllerinden toplamda 17 ödül kazandı. Ödüller arasında En İyi TV Dizisi Performansları ve Jessica Lange'in, Sarah Paulson'un, James Cromwell'in ve Zachary Quinto'nun oyunculuk dalında aday oldukları dallarda Cromwell, En İyi Dizi veya Film dalındaki En İyi Yardımcı Oyuncu ödülünü aldı. 3. Eleştirmenlerin Seçimi Televizyon Ödüllerinde ise Quinto ve Paulson, Yardımcı Oyuncu ödüllerini aldılar.
Antoloji serisi olması dışında Lily Rabe, Naomi Grossman ve John Cromwell gibi bazı kadro oyuncularının, dizinin dördüncü sezonu American Horror Story: Freak Show'daki karakterlerle bağlantısı da vardır.

Retrieved Top-5:
  1. American Horror Story: Asylum (Türkçesi: Amerikan Korku Hikayesi: Akıl Hastanesi), FX tarafından yayınlanan korku-gerilim dizisi American Horror Story'nin ikinci sezonudur. 17 Ekim 2012 - 23 Ocak 2013 tarihleri arasında yayınlanmıştır. İkinci sezonda konu gidişatı ve karakterler ilk sezondan bağımsız olduğu için, dizi American Horror Story başlığı altında bir antoloji serisi olmuştur.
Sezon, 1964 yılında kurgusal bir akıl hastanesi olan Briarcliff Hastanesi'ndeki hastaların, görevlilerin geçmişteki ve gelecekteki hallerini işler. İlk sezondaki karakterlerden Frances Conroy, Jessica Lange, Dylan McDermott, Sarah Paulson, Evan Peters, Zachary Quinto ve Lily Rabe bu sezonda ana karakterleri canlandırmaktadır.
İlk sezon gibi Asylum da eleştirmenlerden ve hayranlardan olumlu eleştiriler aldı. Jessica Lange'in, James Cromwell'in, Zachary Quinto'nun, Sarah Paulson'un ve Lily Rabe'in oyunculukları yer yer çok övüldü. İkinci sezon, Emmy Ödüllerinden toplamda 17 ödül kazandı. Ödüller arasında En İyi TV Dizisi Performansları ve Jessica Lange'in, Sarah Paulson'un, James Cromwell'in ve Zachary Quinto'nun oyunculuk dalında aday oldukları dallarda Cromwell, En İyi Dizi veya Film dalındaki En İyi Yardımcı Oyuncu ödülünü aldı. 3. Eleştirmenlerin Seçimi Televizyon Ödüllerinde ise Quinto ve Paulson, Yardımcı Oyuncu ödüllerini aldılar.
Antoloji serisi olması dışında Lily Rabe, Naomi Grossman ve John Cromwell gibi bazı kadro oyuncularının, dizinin dördüncü sezonu American Horror Story: Freak Show'daki karakterlerle bağlantısı da vardır.

  2. Thingspiel (çoğulu Thingspiele), 1930'larda savaş öncesi Nazi Almanyası'nda kısa süreli popülerlik kazanmış çok disiplinli bir açık hava tiyatrosu performansıydı. Thingplatz veya Thingstätte, bu tür performanslar için özel olarak inşa edilmiş bir açık hava amfitiyatrosuydu. Yaklaşık 400 adet planlanmıştı, ancak 1933 ile 1939 yılları arasında sadece 40 tanesi inşa edildi.

  3. TARDIS (Time And Relative Dimension In Space) (Türkçe: Uzaydaki zaman ve izafi boyut), İngiliz bilimkurgu dizisi Doctor Who'daki uzay ve zamanda herhangi bir yere gidebilen, Gallifrey adlı bir gezegende yaşayan Zaman Lordları tarafından yaratılan bir zaman makinesidir. Bazen adı "The Blue Box" yani "Mavi Kulübe" olarak da geçer.
Asıl şekli olmasa da dışarıdan 1963 yılı Londrasından kalma bir polis telefon kulübesi olarak görünmektedir. Şekil değiştirmesini sağlayan kamuflaj ünitesi bozulduktan sonra Doktor onu tamir etmemiş, öyle bırakmıştır. Aynı anda 6 kişinin kullanabilme kapasitesi olan bu zaman makinesinin aynı zamanda içi dışından daha büyüktür. TARDIS'in içinde uyuma bölümleri, özel ihtiyaç odaları, gardırop, kütüphane, havuz, inziva odası ve kontrol odası bulunuyor. TARDIS içini kontrol edebilir, yeni odalar ekleyebilir ve bazı odaları silebilir. TARDIS, taşıdığı yolculara farklı dilleri anlama ve konuşma yetisi veren bir sisteme sahiptir. Ayrıca her TARDIS'in kendine has bir zekası ve kişiliği vardır.
Doktor onu çalmıştır ya da kendi söylediğine göre ödünç almıştır ve onunla birlikte son büyük zaman savaşından kaçmayı başarmıştır. "The Doctor's Wife" bölümünde TARDIS insan görünümündedir ve Doktor'un kendisini çaldığını değil de kendisinin Doktor'u çaldığını iddia eder.
Doctor Who dizisi İngiltere'nin her yerine yayıldıktan sonra popüler kültür arasına girmeyi de başarmıştır. "TARDIS" kelimesi artık içi dışından büyük görünen herhangi bir şeyin adı olmuştur.
Kavramsal tarihi 1963'te Doctor Who dizisi yazılırken, yazan kişiler Doktor'un zaman makinesinin neye benzemesi gerektiğini tartışmaktaydılar. Belli bir şekilde tutmak için "Police Box" olarak yapılmasına karar verilmişti. Ve the ship's "chameleon circuit" adlı bölümde şeklinin aynı olmasının nedeni açıklanmıştı.
Diğer Zaman Lordları TARDIS'in bir diğer adı olan TT Kapsülü yani Time Travel Capsule (Zaman Yolculuğu Kapsülü) adını kullanmaktadırlar.

  4. Yoshiwara (Japonca: 吉原), Japonya'da Edo'da bulunan bir yūkaku idi. 1617'de kurulmuş olup Tokugawa şogunluğu tarafından 17. yüzyılın başlarında, Kyoto'daki Shimabara ve Osaka'daki Shinmachi'nin yanı sıra 17. yüzyılın başlarında kurulan üç lisanslı ve tanınmış kırmızı fener mahallesinden biriydi.
Şogunluk tarafından, yeni zengin chōnin (tüccar) sınıflarının zevklerini azaltmak ve tecrit etmek için yaratılan, Yoshiwara'da sunulan eğlence, diğer lisanslı bölgelerin yanı sıra, sonunda, moda yoldaşları olarak tanınacak geyşaların ortaya çıkardı. Chōnin sınıfları ve aynı zamanda kırmızı ışıklı bölgelerin üst sınıf nezaketçileri olan oiranların azalmasına neden oldu.
  5. Bermuda, tam adıyla Bermuda Adaları (diğer adıyla Somers Adaları), Atlas Okyanusu'nda, ABD'nin doğu (Kuzey Carolina eyaletindeki Hatteras Burnu'nun yaklaşık 900 km doğusunda) ve Karayipler'in kuzey açıklarında bir takımadadır. Birleşik Krallık'ın denizaşırı topraklarından biridir. Ana ada olan Bermuda adası dâhil yedi ana ada ile 150 küçük ada ve kayalıktan oluşur.
Toplam yüzölçümü 53,3 km²'dir. Başkenti Hamilton'dur, nüfus 65.000 civarındadır.

--------------------------------------------------------------------------------
Query: Su kalitesi değerlendirmesinde hangi standartlar en yaygın olarak kullanılır ve neden?
Correct Answer: Su kalitesi, suyun kimyasal, fiziksel, biyolojik ve radyolojik özelliklerini ifade eder. Bir veya daha fazla biyotik türün gereksinimlerine veya herhangi bir insan ihtiyacına veya amacına göre su durumunun bir ölçüsüdür. En sık olarak, genellikle suyun arıtılmasıyla elde edilen uygunluğun değerlendirilebileceği bir dizi standart referans alınarak kullanılır. Su kalitesini değerlendirmek için kullanılan en yaygın standartlar ekosistemlerin sağlığı, insan temasının güvenliği ve içme suyu ile ilgilidir.

Retrieved Top-1: Su kalitesi, suyun kimyasal, fiziksel, biyolojik ve radyolojik özelliklerini ifade eder. Bir veya daha fazla biyotik türün gereksinimlerine veya herhangi bir insan ihtiyacına veya amacına göre su durumunun bir ölçüsüdür. En sık olarak, genellikle suyun arıtılmasıyla elde edilen uygunluğun değerlendirilebileceği bir dizi standart referans alınarak kullanılır. Su kalitesini değerlendirmek için kullanılan en yaygın standartlar ekosistemlerin sağlığı, insan temasının güvenliği ve içme suyu ile ilgilidir.

Retrieved Top-5:
  1. Su kalitesi, suyun kimyasal, fiziksel, biyolojik ve radyolojik özelliklerini ifade eder. Bir veya daha fazla biyotik türün gereksinimlerine veya herhangi bir insan ihtiyacına veya amacına göre su durumunun bir ölçüsüdür. En sık olarak, genellikle suyun arıtılmasıyla elde edilen uygunluğun değerlendirilebileceği bir dizi standart referans alınarak kullanılır. Su kalitesini değerlendirmek için kullanılan en yaygın standartlar ekosistemlerin sağlığı, insan temasının güvenliği ve içme suyu ile ilgilidir.

  2. Serbest elektron lazeri, lazer ortamı, manyetik bir yapı boyunca serbestçe hareket eden çok hızlı elektronlar içeren bir tür lazerdir. Ayarlanabilir olan ve tüm lazer türleri arasında en geniş frekans aralığına sahip olan serbest elektron lazerleri; mikrodalgalardan, terahertz radyasyonu ile kızılötesine ve görünür spektrum, morötesi ve X ışınlarına kadar uzanan dalga boyuna sahiptir.

  3. Heinrich Eberbach (24 Kasım 1895 - 13 Temmuz 1992), II. Dünya Savaşı sırasında Nazi Almanyası'nın generali (General der Panzertruppe).

  4. Eski Mezopotamya dininde, Lugal-irra ve Meslamta-ea, Kuzey Babil'de bulunan Kisiga köyünde tapılan ikiz tanrılardır.  Kapıların koruyucuları olarak kabul edildiler  ve başlangıçta Yeraltı Dünyası'nın kapılarını koruyan bir dizi ikiz olarak tasfir edilmiş olabilirler.  Neo-Asur döneminde, küçük tasvirleri girişlere gömülürdü,  Lugal-irra her zaman solda ve Meslamta-ea her zaman sağda resmedilirdi.  Birebir aynılardır ve boynuzlu başlıklar takmış olarak gösterilirler. İkisi de bir balta ve bir gürz tutar.  Kendilerinden sonra adlandırılan İkizler takımyıldızı ile tanımlanırlar.

  5. UGC 717 veya Arp 11, Balıklar takımyıldızı yönünde yaklaşık olarak 495,75 MIy (152 Mpc)uzaklıkta bulunan bir çubuklu sarmal galaksidir. Galaksi içinde 20 Kasım 2009 tarihinde Tip IIP süpernova SN 2009lo keşfedilmiştir.
--------------------------------------------------------------------------------
Query: Kedi tuvalet kutularının temizliğinin önemi nedir ve kokuyu engellemek için neler yapılabilir?
Correct Answer: Bazen kum havuzu, kedi tuvalet kutusu veya kedi tuvaleti denilen kap kedilerin yanı sıra tavşanlar, yaban gelincik'ler, minyatür domuz'lar, küçük köpek'ler ve içgüdüsel olarak veya eğitim yoluyla böyle bir yerden yararlanan diğer evcil'ler için bir iç mekan dışkı ve idrar toplama kutusudur. Bir evde serbest dolaşımına izin verilen ancak metabolik atık için dışarı çıkamayan veya her zaman dışarı çıkmayan evcil hayvanlar için kullanılır. Bu hayvanların sahipleri, açık havadaki tehlikelere maruz kalma korkusuyla hayvanlarının dışarıda dolaşmalarına izin vermemeyi tercih eder. Ortalama, kapalı kedilerin ömrü 16.8 yıl iken, açık hava kedilerinin ömrü çok daha kısa, sadece 5.6 yıldır. Bu açık hava tehlikeleri arasında kötü hava durumu, yabani yaşam, trafik veya kedi immün yetmezlik virüsü gibi hastalıklar yer alır.
Vahşi doğada kediler, kolay gömmek için doğal olarak yumuşak veya kumlu toprağa dışkılarlar. Dışkılarını örtmek için patilerini geriye doğru süpürme hareketiyle kullanırlar. Bu içgüdüsel arzuyu harekete geçirmek için, kedi tuvalet kutusunun dibi genellikle 2 inç (5 cm) veya daha az kedi kumu ile doldurulur. Tuvalet kutusu dolgu maddesi, amonyak gibi nemi ve kokuları emen gevşek, tanecikli bir malzemedir. Bazı kum markaları, bu tür kokuları emmek için kabartma tozu içerir veya sahipleri, kutunun altında kedi kumunun altına, ince bir tabaka serpebilir. Altlık malzemesi ayrıca bir kedinin atıklarını gömmelerine izin vererek kokularını gizleme konusundaki içgüdüsel arzusunu da tatmin eder. En yaygın malzeme kildir, ancak geri dönüştürülmüş kâğıt "peletler" ve silika bazlı "kristal" çeşitleri de kullanılır. Bazen, sahibi kedinin doğal içgüdülerini harekete geçirmek istediğinde, doğal kir kullanılır.
Pisliğin içine döküldüğü kedi tuvalet kutusu, uygun şekilde temizlenmediğinde pis bir koku yayar. Tuvalet kutusundan kaçınmayı önlemek için, tuvalet kutusunun bodrum katı veya çamaşır odası gibi evin trafiğin az olduğu alanlarda tutulması tavsiye edilir. Çıkan kokuyu örtmeye veya azaltmaya yardımcı olmak için ticari olarak temin edilebilen özel tuvalet malzeme türleri vardır. Bunlar kabartma tozu, bitki özleri ve/veya kokulu kristaller içerirler. Hava girişi olan bir odada tutulursa, kokuyu evin geri kalanından izole etmek için fırın filtresine oda spreyi eklenebilir.

Retrieved Top-1: Carl Sagan Award for Public Understanding of Science, Council of Scientific Society Presidents tarafından verilen  halk tarafından tanınmış araştırmacı, bilim insanları, eğitimciler ve halka bilimi anlamasını sağlayan kişilere verilir. Ödül ilk olarak ödülle de onuruna aynı adı taşıyan Carl Sagan tarafından verildi.
Retrieved Top-5:
  1. Carl Sagan Award for Public Understanding of Science, Council of Scientific Society Presidents tarafından verilen  halk tarafından tanınmış araştırmacı, bilim insanları, eğitimciler ve halka bilimi anlamasını sağlayan kişilere verilir. Ödül ilk olarak ödülle de onuruna aynı adı taşıyan Carl Sagan tarafından verildi.
  2. Sicim teorisi, parçacık fiziğinde, kuantum mekaniği ile Einstein'in genel görelilik kuramını birleştiren bir teori. "Sicim" adı, klasik yaklaşımda "sıfır boyutlu noktalar" şeklinde tarif edilen atomaltı parçacıkların, aslında "bir boyutlu ve ipliksi varlıklar" olabileceği varsayımına dayanır.
Sicim kuramı, belirli bir biçimde titreşen ipliksilerin, kütle ve yük gibi özelliklere sahip parçacıklar gibi davranabileceğini söyler. 1980'lerde fizikçiler, sicim kuramının doğadaki başlıca dört güç (kütleçekimi, elektromanyetizma, güçlü etkileşim [kuvvetli nükleer güç] ve zayıf etkileşim [zayıf nükleer güç]) ile maddenin tüm türlerini bir kuantum mekanik modelinde (uzun süredir beklenen "birleşik alan teorisi") birleştirme potansiyeline sahip olduğunu fark ettiler.
Sicim kuramı hızla gelişen ve üzerinde çok çalışılan bir alan olmakla birlikte, henüz deneysel gözlemi mümkün olmamış, matematiksel bir modeldir.

  3. Ordnungspolizei (kısaca: OrPo veya Orpo, üniformasının renginden dolayı Grüne Polizei), Nazi Almanyası'nın normal polisi.
Nazi Almanyası döneminde özellikle 1936 - 1945 yılları arasında Sicherheitspolizei (SiPo) ile birlikte rejimi korumakta önemli rolü oynadı.
Milyonlarca Yahudi ve Sovyet savaş esiri Ordnungspolizei mensupları tarafından infaz edildi.

  4. Bazen kum havuzu, kedi tuvalet kutusu veya kedi tuvaleti denilen kap kedilerin yanı sıra tavşanlar, yaban gelincik'ler, minyatür domuz'lar, küçük köpek'ler ve içgüdüsel olarak veya eğitim yoluyla böyle bir yerden yararlanan diğer evcil'ler için bir iç mekan dışkı ve idrar toplama kutusudur. Bir evde serbest dolaşımına izin verilen ancak metabolik atık için dışarı çıkamayan veya her zaman dışarı çıkmayan evcil hayvanlar için kullanılır. Bu hayvanların sahipleri, açık havadaki tehlikelere maruz kalma korkusuyla hayvanlarının dışarıda dolaşmalarına izin vermemeyi tercih eder. Ortalama, kapalı kedilerin ömrü 16.8 yıl iken, açık hava kedilerinin ömrü çok daha kısa, sadece 5.6 yıldır. Bu açık hava tehlikeleri arasında kötü hava durumu, yabani yaşam, trafik veya kedi immün yetmezlik virüsü gibi hastalıklar yer alır.
Vahşi doğada kediler, kolay gömmek için doğal olarak yumuşak veya kumlu toprağa dışkılarlar. Dışkılarını örtmek için patilerini geriye doğru süpürme hareketiyle kullanırlar. Bu içgüdüsel arzuyu harekete geçirmek için, kedi tuvalet kutusunun dibi genellikle 2 inç (5 cm) veya daha az kedi kumu ile doldurulur. Tuvalet kutusu dolgu maddesi, amonyak gibi nemi ve kokuları emen gevşek, tanecikli bir malzemedir. Bazı kum markaları, bu tür kokuları emmek için kabartma tozu içerir veya sahipleri, kutunun altında kedi kumunun altına, ince bir tabaka serpebilir. Altlık malzemesi ayrıca bir kedinin atıklarını gömmelerine izin vererek kokularını gizleme konusundaki içgüdüsel arzusunu da tatmin eder. En yaygın malzeme kildir, ancak geri dönüştürülmüş kâğıt "peletler" ve silika bazlı "kristal" çeşitleri de kullanılır. Bazen, sahibi kedinin doğal içgüdülerini harekete geçirmek istediğinde, doğal kir kullanılır.
Pisliğin içine döküldüğü kedi tuvalet kutusu, uygun şekilde temizlenmediğinde pis bir koku yayar. Tuvalet kutusundan kaçınmayı önlemek için, tuvalet kutusunun bodrum katı veya çamaşır odası gibi evin trafiğin az olduğu alanlarda tutulması tavsiye edilir. Çıkan kokuyu örtmeye veya azaltmaya yardımcı olmak için ticari olarak temin edilebilen özel tuvalet malzeme türleri vardır. Bunlar kabartma tozu, bitki özleri ve/veya kokulu kristaller içerirler. Hava girişi olan bir odada tutulursa, kokuyu evin geri kalanından izole etmek için fırın filtresine oda spreyi eklenebilir.

  5. Dilivium, bir jeoloji terimidir. Sel ve taşkın sularının yüzeysel akışı sırasında bünyesinde taşıdığı kil ve benzeri alüvyonları yavaş ve istikrarlı bir şekilde biriktirmesiyle oluşan kayaçlardır. Bu terim eskiden Nuh tufanının neden olduğu sanılan kaya kil katmanlarına verilirdi.
20. yüzyılın sonlarında Rus coğrafyacı Alexei Rudoy dilivium terimini Altay havzası dağlar asındaki Buzul Çağı dev buzul barajı göllerinin katastrofik patlamaları sonucu oluşan katmanların tanımı için önermiştir. Bu göllerin en genişleri, Chuya ve Kuray, yüzlerce kilometre su hacmine sahipti ve bunların zirve hidrografi akış hızındaki tahliye oranı, Kuzey Amerika’daki meşhur Pleistosen Lake Missoula selinin azami oranlarını aşmıştır.

--------------------------------------------------------------------------------

### **fine 2**

In [ ]:
# set up Trainer
training_args3 = TrainingArguments(
    output_dir="./results",
    eval_strategy="epoch",
    save_strategy="epoch",
    logging_dir="./logs",
    logging_steps=10,
    report_to="tensorboard",
    learning_rate=1e-3,
    per_device_train_batch_size=32,
    per_device_eval_batch_size=32,
    num_train_epochs=10,
    weight_decay=0.01,
    save_total_limit=2,
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss"
)

trainer3 = Trainer(
    model=fine_tune_model,
    args=training_args3,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    compute_metrics=compute_metrics,
)

# train the model
trainer3.train()

# save the fine-tuned model
fine_tune_model.save_pretrained("./fine_tuned_model3")
tokenizer.save_pretrained("./fine_tuned_model3")
print("Fine-tuning complete and model3 saved!")

Fine-tuning complete and model3 saved!

In [ ]:
# evaluate the fine-tuned model
fine3_top1, fine3_top5, samples_fine3 = evaluate_classifier(fine_tune_data, tokenizer, fine_tune_model)
print(f"Classifier Top-1 Accuracy: {fine3_top1:.2%}")
print(f"Classifier Top-5 Accuracy: {fine3_top5:.2%}")

Classifier Top-1 Accuracy: 29.00%
Classifier Top-5 Accuracy: 100.00%

In [ ]:
specific_indices = [0, 44,88]
display_retrieval_results(samples_fine3, queries=samples_fine3["all_retrieved"].iloc[specific_indices]["query"].tolist())

Retrieval Results:
================================================================================
Query: Bermuda Adaları'nın Birleşik Krallık'a bağlı bir bölge olmasının tarihi sebepleri nelerdir?
Correct Answer: Bermuda, tam adıyla Bermuda Adaları (diğer adıyla Somers Adaları), Atlas Okyanusu'nda, ABD'nin doğu (Kuzey Carolina eyaletindeki Hatteras Burnu'nun yaklaşık 900 km doğusunda) ve Karayipler'in kuzey açıklarında bir takımadadır. Birleşik Krallık'ın denizaşırı topraklarından biridir. Ana ada olan Bermuda adası dâhil yedi ana ada ile 150 küçük ada ve kayalıktan oluşur.
Toplam yüzölçümü 53,3 km²'dir. Başkenti Hamilton'dur, nüfus 65.000 civarındadır.

Retrieved Top-1: Bermuda, tam adıyla Bermuda Adaları (diğer adıyla Somers Adaları), Atlas Okyanusu'nda, ABD'nin doğu (Kuzey Carolina eyaletindeki Hatteras Burnu'nun yaklaşık 900 km doğusunda) ve Karayipler'in kuzey açıklarında bir takımadadır. Birleşik Krallık'ın denizaşırı topraklarından biridir. Ana ada olan Bermuda adası dâhil yedi ana ada ile 150 küçük ada ve kayalıktan oluşur.
Toplam yüzölçümü 53,3 km²'dir. Başkenti Hamilton'dur, nüfus 65.000 civarındadır.

Retrieved Top-5:
  1. Bermuda, tam adıyla Bermuda Adaları (diğer adıyla Somers Adaları), Atlas Okyanusu'nda, ABD'nin doğu (Kuzey Carolina eyaletindeki Hatteras Burnu'nun yaklaşık 900 km doğusunda) ve Karayipler'in kuzey açıklarında bir takımadadır. Birleşik Krallık'ın denizaşırı topraklarından biridir. Ana ada olan Bermuda adası dâhil yedi ana ada ile 150 küçük ada ve kayalıktan oluşur.
Toplam yüzölçümü 53,3 km²'dir. Başkenti Hamilton'dur, nüfus 65.000 civarındadır.

  2. American Horror Story: Asylum (Türkçesi: Amerikan Korku Hikayesi: Akıl Hastanesi), FX tarafından yayınlanan korku-gerilim dizisi American Horror Story'nin ikinci sezonudur. 17 Ekim 2012 - 23 Ocak 2013 tarihleri arasında yayınlanmıştır. İkinci sezonda konu gidişatı ve karakterler ilk sezondan bağımsız olduğu için, dizi American Horror Story başlığı altında bir antoloji serisi olmuştur.
Sezon, 1964 yılında kurgusal bir akıl hastanesi olan Briarcliff Hastanesi'ndeki hastaların, görevlilerin geçmişteki ve gelecekteki hallerini işler. İlk sezondaki karakterlerden Frances Conroy, Jessica Lange, Dylan McDermott, Sarah Paulson, Evan Peters, Zachary Quinto ve Lily Rabe bu sezonda ana karakterleri canlandırmaktadır.
İlk sezon gibi Asylum da eleştirmenlerden ve hayranlardan olumlu eleştiriler aldı. Jessica Lange'in, James Cromwell'in, Zachary Quinto'nun, Sarah Paulson'un ve Lily Rabe'in oyunculukları yer yer çok övüldü. İkinci sezon, Emmy Ödüllerinden toplamda 17 ödül kazandı. Ödüller arasında En İyi TV Dizisi Performansları ve Jessica Lange'in, Sarah Paulson'un, James Cromwell'in ve Zachary Quinto'nun oyunculuk dalında aday oldukları dallarda Cromwell, En İyi Dizi veya Film dalındaki En İyi Yardımcı Oyuncu ödülünü aldı. 3. Eleştirmenlerin Seçimi Televizyon Ödüllerinde ise Quinto ve Paulson, Yardımcı Oyuncu ödüllerini aldılar.
Antoloji serisi olması dışında Lily Rabe, Naomi Grossman ve John Cromwell gibi bazı kadro oyuncularının, dizinin dördüncü sezonu American Horror Story: Freak Show'daki karakterlerle bağlantısı da vardır.

  3. Thingspiel (çoğulu Thingspiele), 1930'larda savaş öncesi Nazi Almanyası'nda kısa süreli popülerlik kazanmış çok disiplinli bir açık hava tiyatrosu performansıydı. Thingplatz veya Thingstätte, bu tür performanslar için özel olarak inşa edilmiş bir açık hava amfitiyatrosuydu. Yaklaşık 400 adet planlanmıştı, ancak 1933 ile 1939 yılları arasında sadece 40 tanesi inşa edildi.

  4. TARDIS (Time And Relative Dimension In Space) (Türkçe: Uzaydaki zaman ve izafi boyut), İngiliz bilimkurgu dizisi Doctor Who'daki uzay ve zamanda herhangi bir yere gidebilen, Gallifrey adlı bir gezegende yaşayan Zaman Lordları tarafından yaratılan bir zaman makinesidir. Bazen adı "The Blue Box" yani "Mavi Kulübe" olarak da geçer.
Asıl şekli olmasa da dışarıdan 1963 yılı Londrasından kalma bir polis telefon kulübesi olarak görünmektedir. Şekil değiştirmesini sağlayan kamuflaj ünitesi bozulduktan sonra Doktor onu tamir etmemiş, öyle bırakmıştır. Aynı anda 6 kişinin kullanabilme kapasitesi olan bu zaman makinesinin aynı zamanda içi dışından daha büyüktür. TARDIS'in içinde uyuma bölümleri, özel ihtiyaç odaları, gardırop, kütüphane, havuz, inziva odası ve kontrol odası bulunuyor. TARDIS içini kontrol edebilir, yeni odalar ekleyebilir ve bazı odaları silebilir. TARDIS, taşıdığı yolculara farklı dilleri anlama ve konuşma yetisi veren bir sisteme sahiptir. Ayrıca her TARDIS'in kendine has bir zekası ve kişiliği vardır.
Doktor onu çalmıştır ya da kendi söylediğine göre ödünç almıştır ve onunla birlikte son büyük zaman savaşından kaçmayı başarmıştır. "The Doctor's Wife" bölümünde TARDIS insan görünümündedir ve Doktor'un kendisini çaldığını değil de kendisinin Doktor'u çaldığını iddia eder.
Doctor Who dizisi İngiltere'nin her yerine yayıldıktan sonra popüler kültür arasına girmeyi de başarmıştır. "TARDIS" kelimesi artık içi dışından büyük görünen herhangi bir şeyin adı olmuştur.
Kavramsal tarihi 1963'te Doctor Who dizisi yazılırken, yazan kişiler Doktor'un zaman makinesinin neye benzemesi gerektiğini tartışmaktaydılar. Belli bir şekilde tutmak için "Police Box" olarak yapılmasına karar verilmişti. Ve the ship's "chameleon circuit" adlı bölümde şeklinin aynı olmasının nedeni açıklanmıştı.
Diğer Zaman Lordları TARDIS'in bir diğer adı olan TT Kapsülü yani Time Travel Capsule (Zaman Yolculuğu Kapsülü) adını kullanmaktadırlar.

  5. Yoshiwara (Japonca: 吉原), Japonya'da Edo'da bulunan bir yūkaku idi. 1617'de kurulmuş olup Tokugawa şogunluğu tarafından 17. yüzyılın başlarında, Kyoto'daki Shimabara ve Osaka'daki Shinmachi'nin yanı sıra 17. yüzyılın başlarında kurulan üç lisanslı ve tanınmış kırmızı fener mahallesinden biriydi.
Şogunluk tarafından, yeni zengin chōnin (tüccar) sınıflarının zevklerini azaltmak ve tecrit etmek için yaratılan, Yoshiwara'da sunulan eğlence, diğer lisanslı bölgelerin yanı sıra, sonunda, moda yoldaşları olarak tanınacak geyşaların ortaya çıkardı. Chōnin sınıfları ve aynı zamanda kırmızı ışıklı bölgelerin üst sınıf nezaketçileri olan oiranların azalmasına neden oldu.
--------------------------------------------------------------------------------
Query: Su kalitesi değerlendirmesinde hangi standartlar en yaygın olarak kullanılır ve neden?
Correct Answer: Su kalitesi, suyun kimyasal, fiziksel, biyolojik ve radyolojik özelliklerini ifade eder. Bir veya daha fazla biyotik türün gereksinimlerine veya herhangi bir insan ihtiyacına veya amacına göre su durumunun bir ölçüsüdür. En sık olarak, genellikle suyun arıtılmasıyla elde edilen uygunluğun değerlendirilebileceği bir dizi standart referans alınarak kullanılır. Su kalitesini değerlendirmek için kullanılan en yaygın standartlar ekosistemlerin sağlığı, insan temasının güvenliği ve içme suyu ile ilgilidir.

Retrieved Top-1: Serbest elektron lazeri, lazer ortamı, manyetik bir yapı boyunca serbestçe hareket eden çok hızlı elektronlar içeren bir tür lazerdir. Ayarlanabilir olan ve tüm lazer türleri arasında en geniş frekans aralığına sahip olan serbest elektron lazerleri; mikrodalgalardan, terahertz radyasyonu ile kızılötesine ve görünür spektrum, morötesi ve X ışınlarına kadar uzanan dalga boyuna sahiptir.

Retrieved Top-5:
  1. Serbest elektron lazeri, lazer ortamı, manyetik bir yapı boyunca serbestçe hareket eden çok hızlı elektronlar içeren bir tür lazerdir. Ayarlanabilir olan ve tüm lazer türleri arasında en geniş frekans aralığına sahip olan serbest elektron lazerleri; mikrodalgalardan, terahertz radyasyonu ile kızılötesine ve görünür spektrum, morötesi ve X ışınlarına kadar uzanan dalga boyuna sahiptir.

  2. Heinrich Eberbach (24 Kasım 1895 - 13 Temmuz 1992), II. Dünya Savaşı sırasında Nazi Almanyası'nın generali (General der Panzertruppe).

  3. Su kalitesi, suyun kimyasal, fiziksel, biyolojik ve radyolojik özelliklerini ifade eder. Bir veya daha fazla biyotik türün gereksinimlerine veya herhangi bir insan ihtiyacına veya amacına göre su durumunun bir ölçüsüdür. En sık olarak, genellikle suyun arıtılmasıyla elde edilen uygunluğun değerlendirilebileceği bir dizi standart referans alınarak kullanılır. Su kalitesini değerlendirmek için kullanılan en yaygın standartlar ekosistemlerin sağlığı, insan temasının güvenliği ve içme suyu ile ilgilidir.

  4. Eski Mezopotamya dininde, Lugal-irra ve Meslamta-ea, Kuzey Babil'de bulunan Kisiga köyünde tapılan ikiz tanrılardır.  Kapıların koruyucuları olarak kabul edildiler  ve başlangıçta Yeraltı Dünyası'nın kapılarını koruyan bir dizi ikiz olarak tasfir edilmiş olabilirler.  Neo-Asur döneminde, küçük tasvirleri girişlere gömülürdü,  Lugal-irra her zaman solda ve Meslamta-ea her zaman sağda resmedilirdi.  Birebir aynılardır ve boynuzlu başlıklar takmış olarak gösterilirler. İkisi de bir balta ve bir gürz tutar.  Kendilerinden sonra adlandırılan İkizler takımyıldızı ile tanımlanırlar.

  5. UGC 717 veya Arp 11, Balıklar takımyıldızı yönünde yaklaşık olarak 495,75 MIy (152 Mpc)uzaklıkta bulunan bir çubuklu sarmal galaksidir. Galaksi içinde 20 Kasım 2009 tarihinde Tip IIP süpernova SN 2009lo keşfedilmiştir.
--------------------------------------------------------------------------------
Query: Kedi tuvalet kutularının temizliğinin önemi nedir ve kokuyu engellemek için neler yapılabilir?
Correct Answer: Bazen kum havuzu, kedi tuvalet kutusu veya kedi tuvaleti denilen kap kedilerin yanı sıra tavşanlar, yaban gelincik'ler, minyatür domuz'lar, küçük köpek'ler ve içgüdüsel olarak veya eğitim yoluyla böyle bir yerden yararlanan diğer evcil'ler için bir iç mekan dışkı ve idrar toplama kutusudur. Bir evde serbest dolaşımına izin verilen ancak metabolik atık için dışarı çıkamayan veya her zaman dışarı çıkmayan evcil hayvanlar için kullanılır. Bu hayvanların sahipleri, açık havadaki tehlikelere maruz kalma korkusuyla hayvanlarının dışarıda dolaşmalarına izin vermemeyi tercih eder. Ortalama, kapalı kedilerin ömrü 16.8 yıl iken, açık hava kedilerinin ömrü çok daha kısa, sadece 5.6 yıldır. Bu açık hava tehlikeleri arasında kötü hava durumu, yabani yaşam, trafik veya kedi immün yetmezlik virüsü gibi hastalıklar yer alır.
Vahşi doğada kediler, kolay gömmek için doğal olarak yumuşak veya kumlu toprağa dışkılarlar. Dışkılarını örtmek için patilerini geriye doğru süpürme hareketiyle kullanırlar. Bu içgüdüsel arzuyu harekete geçirmek için, kedi tuvalet kutusunun dibi genellikle 2 inç (5 cm) veya daha az kedi kumu ile doldurulur. Tuvalet kutusu dolgu maddesi, amonyak gibi nemi ve kokuları emen gevşek, tanecikli bir malzemedir. Bazı kum markaları, bu tür kokuları emmek için kabartma tozu içerir veya sahipleri, kutunun altında kedi kumunun altına, ince bir tabaka serpebilir. Altlık malzemesi ayrıca bir kedinin atıklarını gömmelerine izin vererek kokularını gizleme konusundaki içgüdüsel arzusunu da tatmin eder. En yaygın malzeme kildir, ancak geri dönüştürülmüş kâğıt "peletler" ve silika bazlı "kristal" çeşitleri de kullanılır. Bazen, sahibi kedinin doğal içgüdülerini harekete geçirmek istediğinde, doğal kir kullanılır.
Pisliğin içine döküldüğü kedi tuvalet kutusu, uygun şekilde temizlenmediğinde pis bir koku yayar. Tuvalet kutusundan kaçınmayı önlemek için, tuvalet kutusunun bodrum katı veya çamaşır odası gibi evin trafiğin az olduğu alanlarda tutulması tavsiye edilir. Çıkan kokuyu örtmeye veya azaltmaya yardımcı olmak için ticari olarak temin edilebilen özel tuvalet malzeme türleri vardır. Bunlar kabartma tozu, bitki özleri ve/veya kokulu kristaller içerirler. Hava girişi olan bir odada tutulursa, kokuyu evin geri kalanından izole etmek için fırın filtresine oda spreyi eklenebilir.

Retrieved Top-1: Ordnungspolizei (kısaca: OrPo veya Orpo, üniformasının renginden dolayı Grüne Polizei), Nazi Almanyası'nın normal polisi.
Nazi Almanyası döneminde özellikle 1936 - 1945 yılları arasında Sicherheitspolizei (SiPo) ile birlikte rejimi korumakta önemli rolü oynadı.
Milyonlarca Yahudi ve Sovyet savaş esiri Ordnungspolizei mensupları tarafından infaz edildi.

Retrieved Top-5:
  1. Ordnungspolizei (kısaca: OrPo veya Orpo, üniformasının renginden dolayı Grüne Polizei), Nazi Almanyası'nın normal polisi.
Nazi Almanyası döneminde özellikle 1936 - 1945 yılları arasında Sicherheitspolizei (SiPo) ile birlikte rejimi korumakta önemli rolü oynadı.
Milyonlarca Yahudi ve Sovyet savaş esiri Ordnungspolizei mensupları tarafından infaz edildi.

  2. Carl Sagan Award for Public Understanding of Science, Council of Scientific Society Presidents tarafından verilen  halk tarafından tanınmış araştırmacı, bilim insanları, eğitimciler ve halka bilimi anlamasını sağlayan kişilere verilir. Ödül ilk olarak ödülle de onuruna aynı adı taşıyan Carl Sagan tarafından verildi.
  3. Sicim teorisi, parçacık fiziğinde, kuantum mekaniği ile Einstein'in genel görelilik kuramını birleştiren bir teori. "Sicim" adı, klasik yaklaşımda "sıfır boyutlu noktalar" şeklinde tarif edilen atomaltı parçacıkların, aslında "bir boyutlu ve ipliksi varlıklar" olabileceği varsayımına dayanır.
Sicim kuramı, belirli bir biçimde titreşen ipliksilerin, kütle ve yük gibi özelliklere sahip parçacıklar gibi davranabileceğini söyler. 1980'lerde fizikçiler, sicim kuramının doğadaki başlıca dört güç (kütleçekimi, elektromanyetizma, güçlü etkileşim [kuvvetli nükleer güç] ve zayıf etkileşim [zayıf nükleer güç]) ile maddenin tüm türlerini bir kuantum mekanik modelinde (uzun süredir beklenen "birleşik alan teorisi") birleştirme potansiyeline sahip olduğunu fark ettiler.
Sicim kuramı hızla gelişen ve üzerinde çok çalışılan bir alan olmakla birlikte, henüz deneysel gözlemi mümkün olmamış, matematiksel bir modeldir.

  4. Dilivium, bir jeoloji terimidir. Sel ve taşkın sularının yüzeysel akışı sırasında bünyesinde taşıdığı kil ve benzeri alüvyonları yavaş ve istikrarlı bir şekilde biriktirmesiyle oluşan kayaçlardır. Bu terim eskiden Nuh tufanının neden olduğu sanılan kaya kil katmanlarına verilirdi.
20. yüzyılın sonlarında Rus coğrafyacı Alexei Rudoy dilivium terimini Altay havzası dağlar asındaki Buzul Çağı dev buzul barajı göllerinin katastrofik patlamaları sonucu oluşan katmanların tanımı için önermiştir. Bu göllerin en genişleri, Chuya ve Kuray, yüzlerce kilometre su hacmine sahipti ve bunların zirve hidrografi akış hızındaki tahliye oranı, Kuzey Amerika’daki meşhur Pleistosen Lake Missoula selinin azami oranlarını aşmıştır.

  5. Bazen kum havuzu, kedi tuvalet kutusu veya kedi tuvaleti denilen kap kedilerin yanı sıra tavşanlar, yaban gelincik'ler, minyatür domuz'lar, küçük köpek'ler ve içgüdüsel olarak veya eğitim yoluyla böyle bir yerden yararlanan diğer evcil'ler için bir iç mekan dışkı ve idrar toplama kutusudur. Bir evde serbest dolaşımına izin verilen ancak metabolik atık için dışarı çıkamayan veya her zaman dışarı çıkmayan evcil hayvanlar için kullanılır. Bu hayvanların sahipleri, açık havadaki tehlikelere maruz kalma korkusuyla hayvanlarının dışarıda dolaşmalarına izin vermemeyi tercih eder. Ortalama, kapalı kedilerin ömrü 16.8 yıl iken, açık hava kedilerinin ömrü çok daha kısa, sadece 5.6 yıldır. Bu açık hava tehlikeleri arasında kötü hava durumu, yabani yaşam, trafik veya kedi immün yetmezlik virüsü gibi hastalıklar yer alır.
Vahşi doğada kediler, kolay gömmek için doğal olarak yumuşak veya kumlu toprağa dışkılarlar. Dışkılarını örtmek için patilerini geriye doğru süpürme hareketiyle kullanırlar. Bu içgüdüsel arzuyu harekete geçirmek için, kedi tuvalet kutusunun dibi genellikle 2 inç (5 cm) veya daha az kedi kumu ile doldurulur. Tuvalet kutusu dolgu maddesi, amonyak gibi nemi ve kokuları emen gevşek, tanecikli bir malzemedir. Bazı kum markaları, bu tür kokuları emmek için kabartma tozu içerir veya sahipleri, kutunun altında kedi kumunun altına, ince bir tabaka serpebilir. Altlık malzemesi ayrıca bir kedinin atıklarını gömmelerine izin vererek kokularını gizleme konusundaki içgüdüsel arzusunu da tatmin eder. En yaygın malzeme kildir, ancak geri dönüştürülmüş kâğıt "peletler" ve silika bazlı "kristal" çeşitleri de kullanılır. Bazen, sahibi kedinin doğal içgüdülerini harekete geçirmek istediğinde, doğal kir kullanılır.
Pisliğin içine döküldüğü kedi tuvalet kutusu, uygun şekilde temizlenmediğinde pis bir koku yayar. Tuvalet kutusundan kaçınmayı önlemek için, tuvalet kutusunun bodrum katı veya çamaşır odası gibi evin trafiğin az olduğu alanlarda tutulması tavsiye edilir. Çıkan kokuyu örtmeye veya azaltmaya yardımcı olmak için ticari olarak temin edilebilen özel tuvalet malzeme türleri vardır. Bunlar kabartma tozu, bitki özleri ve/veya kokulu kristaller içerirler. Hava girişi olan bir odada tutulursa, kokuyu evin geri kalanından izole etmek için fırın filtresine oda spreyi eklenebilir.

--------------------------------------------------------------------------------

## **fine 3**

In [ ]:
# set up Trainer
training_args4 = TrainingArguments(
    output_dir="./results",
    eval_strategy="epoch",
    save_strategy="epoch",
    logging_dir="./logs",
    logging_steps=1,
    report_to="tensorboard",
    learning_rate=5e-5,
    per_device_train_batch_size=64,
    per_device_eval_batch_size=64,
    num_train_epochs=15,
    weight_decay=0.01,
    save_total_limit=2,
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss"
)

trainer4 = Trainer(
    model=fine_tune_model,
    args=training_args4,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    compute_metrics=compute_metrics,
)

# train the model
trainer4.train()

# save the fine-tuned model
fine_tune_model.save_pretrained("./fine_tuned_model4")
tokenizer.save_pretrained("./fine_tuned_model4")
print("Fine-tuning complete and model4 saved!")

Fine-tuning complete and model4 saved!

In [ ]:
# evaluate the fine-tuned model
fine4_top1, fine4_top5, samples_fine4 = evaluate_classifier(fine_tune_data, tokenizer, fine_tune_model)
print(f"Classifier Top-1 Accuracy: {fine4_top1:.2%}")
print(f"Classifier Top-5 Accuracy: {fine4_top5:.2%}")

Classifier Top-1 Accuracy: 75.00%
Classifier Top-5 Accuracy: 100.00%

In [ ]:
specific_indices = [0, 44,88]
display_retrieval_results(samples_fine4, queries=samples_fine4["all_retrieved"].iloc[specific_indices]["query"].tolist())

Retrieval Results:
================================================================================
Query: Bermuda Adaları'nın Birleşik Krallık'a bağlı bir bölge olmasının tarihi sebepleri nelerdir?
Correct Answer: Bermuda, tam adıyla Bermuda Adaları (diğer adıyla Somers Adaları), Atlas Okyanusu'nda, ABD'nin doğu (Kuzey Carolina eyaletindeki Hatteras Burnu'nun yaklaşık 900 km doğusunda) ve Karayipler'in kuzey açıklarında bir takımadadır. Birleşik Krallık'ın denizaşırı topraklarından biridir. Ana ada olan Bermuda adası dâhil yedi ana ada ile 150 küçük ada ve kayalıktan oluşur.
Toplam yüzölçümü 53,3 km²'dir. Başkenti Hamilton'dur, nüfus 65.000 civarındadır.

Retrieved Top-1: Ekonomi tarihi veya iktisat tarihi, geçmişte yaşanan ekonomik olguların nasıl geliştiği konusunda çalışan bilim dalı. Ekonomi tarihinin analizi; tarihsel durumlara ekonomik teorilerin uygulanması, tarihsel yöntemler ve istatistiksel yöntemlerin bir kombinasyonu kullanılarak ele alınır. Bu başlık, sosyal tarihin örtüşen bazı alanları (demografik tarih gibi) ve işletme tarihi konularını içerir. Ekonomi tarihinin kantitatif incelenmesine, cliometri de denmektedir.

Retrieved Top-5:
  1. Ekonomi tarihi veya iktisat tarihi, geçmişte yaşanan ekonomik olguların nasıl geliştiği konusunda çalışan bilim dalı. Ekonomi tarihinin analizi; tarihsel durumlara ekonomik teorilerin uygulanması, tarihsel yöntemler ve istatistiksel yöntemlerin bir kombinasyonu kullanılarak ele alınır. Bu başlık, sosyal tarihin örtüşen bazı alanları (demografik tarih gibi) ve işletme tarihi konularını içerir. Ekonomi tarihinin kantitatif incelenmesine, cliometri de denmektedir.

  2. TARDIS (Time And Relative Dimension In Space) (Türkçe: Uzaydaki zaman ve izafi boyut), İngiliz bilimkurgu dizisi Doctor Who'daki uzay ve zamanda herhangi bir yere gidebilen, Gallifrey adlı bir gezegende yaşayan Zaman Lordları tarafından yaratılan bir zaman makinesidir. Bazen adı "The Blue Box" yani "Mavi Kulübe" olarak da geçer.
Asıl şekli olmasa da dışarıdan 1963 yılı Londrasından kalma bir polis telefon kulübesi olarak görünmektedir. Şekil değiştirmesini sağlayan kamuflaj ünitesi bozulduktan sonra Doktor onu tamir etmemiş, öyle bırakmıştır. Aynı anda 6 kişinin kullanabilme kapasitesi olan bu zaman makinesinin aynı zamanda içi dışından daha büyüktür. TARDIS'in içinde uyuma bölümleri, özel ihtiyaç odaları, gardırop, kütüphane, havuz, inziva odası ve kontrol odası bulunuyor. TARDIS içini kontrol edebilir, yeni odalar ekleyebilir ve bazı odaları silebilir. TARDIS, taşıdığı yolculara farklı dilleri anlama ve konuşma yetisi veren bir sisteme sahiptir. Ayrıca her TARDIS'in kendine has bir zekası ve kişiliği vardır.
Doktor onu çalmıştır ya da kendi söylediğine göre ödünç almıştır ve onunla birlikte son büyük zaman savaşından kaçmayı başarmıştır. "The Doctor's Wife" bölümünde TARDIS insan görünümündedir ve Doktor'un kendisini çaldığını değil de kendisinin Doktor'u çaldığını iddia eder.
Doctor Who dizisi İngiltere'nin her yerine yayıldıktan sonra popüler kültür arasına girmeyi de başarmıştır. "TARDIS" kelimesi artık içi dışından büyük görünen herhangi bir şeyin adı olmuştur.
Kavramsal tarihi 1963'te Doctor Who dizisi yazılırken, yazan kişiler Doktor'un zaman makinesinin neye benzemesi gerektiğini tartışmaktaydılar. Belli bir şekilde tutmak için "Police Box" olarak yapılmasına karar verilmişti. Ve the ship's "chameleon circuit" adlı bölümde şeklinin aynı olmasının nedeni açıklanmıştı.
Diğer Zaman Lordları TARDIS'in bir diğer adı olan TT Kapsülü yani Time Travel Capsule (Zaman Yolculuğu Kapsülü) adını kullanmaktadırlar.

  3. Thingspiel (çoğulu Thingspiele), 1930'larda savaş öncesi Nazi Almanyası'nda kısa süreli popülerlik kazanmış çok disiplinli bir açık hava tiyatrosu performansıydı. Thingplatz veya Thingstätte, bu tür performanslar için özel olarak inşa edilmiş bir açık hava amfitiyatrosuydu. Yaklaşık 400 adet planlanmıştı, ancak 1933 ile 1939 yılları arasında sadece 40 tanesi inşa edildi.

  4. Yoshiwara (Japonca: 吉原), Japonya'da Edo'da bulunan bir yūkaku idi. 1617'de kurulmuş olup Tokugawa şogunluğu tarafından 17. yüzyılın başlarında, Kyoto'daki Shimabara ve Osaka'daki Shinmachi'nin yanı sıra 17. yüzyılın başlarında kurulan üç lisanslı ve tanınmış kırmızı fener mahallesinden biriydi.
Şogunluk tarafından, yeni zengin chōnin (tüccar) sınıflarının zevklerini azaltmak ve tecrit etmek için yaratılan, Yoshiwara'da sunulan eğlence, diğer lisanslı bölgelerin yanı sıra, sonunda, moda yoldaşları olarak tanınacak geyşaların ortaya çıkardı. Chōnin sınıfları ve aynı zamanda kırmızı ışıklı bölgelerin üst sınıf nezaketçileri olan oiranların azalmasına neden oldu.
  5. Bermuda, tam adıyla Bermuda Adaları (diğer adıyla Somers Adaları), Atlas Okyanusu'nda, ABD'nin doğu (Kuzey Carolina eyaletindeki Hatteras Burnu'nun yaklaşık 900 km doğusunda) ve Karayipler'in kuzey açıklarında bir takımadadır. Birleşik Krallık'ın denizaşırı topraklarından biridir. Ana ada olan Bermuda adası dâhil yedi ana ada ile 150 küçük ada ve kayalıktan oluşur.
Toplam yüzölçümü 53,3 km²'dir. Başkenti Hamilton'dur, nüfus 65.000 civarındadır.

--------------------------------------------------------------------------------
Query: Su kalitesi değerlendirmesinde hangi standartlar en yaygın olarak kullanılır ve neden?
Correct Answer: Su kalitesi, suyun kimyasal, fiziksel, biyolojik ve radyolojik özelliklerini ifade eder. Bir veya daha fazla biyotik türün gereksinimlerine veya herhangi bir insan ihtiyacına veya amacına göre su durumunun bir ölçüsüdür. En sık olarak, genellikle suyun arıtılmasıyla elde edilen uygunluğun değerlendirilebileceği bir dizi standart referans alınarak kullanılır. Su kalitesini değerlendirmek için kullanılan en yaygın standartlar ekosistemlerin sağlığı, insan temasının güvenliği ve içme suyu ile ilgilidir.

Retrieved Top-1: Su kalitesi, suyun kimyasal, fiziksel, biyolojik ve radyolojik özelliklerini ifade eder. Bir veya daha fazla biyotik türün gereksinimlerine veya herhangi bir insan ihtiyacına veya amacına göre su durumunun bir ölçüsüdür. En sık olarak, genellikle suyun arıtılmasıyla elde edilen uygunluğun değerlendirilebileceği bir dizi standart referans alınarak kullanılır. Su kalitesini değerlendirmek için kullanılan en yaygın standartlar ekosistemlerin sağlığı, insan temasının güvenliği ve içme suyu ile ilgilidir.

Retrieved Top-5:
  1. Su kalitesi, suyun kimyasal, fiziksel, biyolojik ve radyolojik özelliklerini ifade eder. Bir veya daha fazla biyotik türün gereksinimlerine veya herhangi bir insan ihtiyacına veya amacına göre su durumunun bir ölçüsüdür. En sık olarak, genellikle suyun arıtılmasıyla elde edilen uygunluğun değerlendirilebileceği bir dizi standart referans alınarak kullanılır. Su kalitesini değerlendirmek için kullanılan en yaygın standartlar ekosistemlerin sağlığı, insan temasının güvenliği ve içme suyu ile ilgilidir.

  2. Serbest elektron lazeri, lazer ortamı, manyetik bir yapı boyunca serbestçe hareket eden çok hızlı elektronlar içeren bir tür lazerdir. Ayarlanabilir olan ve tüm lazer türleri arasında en geniş frekans aralığına sahip olan serbest elektron lazerleri; mikrodalgalardan, terahertz radyasyonu ile kızılötesine ve görünür spektrum, morötesi ve X ışınlarına kadar uzanan dalga boyuna sahiptir.

  3. Eski Mezopotamya dininde, Lugal-irra ve Meslamta-ea, Kuzey Babil'de bulunan Kisiga köyünde tapılan ikiz tanrılardır.  Kapıların koruyucuları olarak kabul edildiler  ve başlangıçta Yeraltı Dünyası'nın kapılarını koruyan bir dizi ikiz olarak tasfir edilmiş olabilirler.  Neo-Asur döneminde, küçük tasvirleri girişlere gömülürdü,  Lugal-irra her zaman solda ve Meslamta-ea her zaman sağda resmedilirdi.  Birebir aynılardır ve boynuzlu başlıklar takmış olarak gösterilirler. İkisi de bir balta ve bir gürz tutar.  Kendilerinden sonra adlandırılan İkizler takımyıldızı ile tanımlanırlar.

  4. Heinrich Eberbach (24 Kasım 1895 - 13 Temmuz 1992), II. Dünya Savaşı sırasında Nazi Almanyası'nın generali (General der Panzertruppe).

  5. UGC 717 veya Arp 11, Balıklar takımyıldızı yönünde yaklaşık olarak 495,75 MIy (152 Mpc)uzaklıkta bulunan bir çubuklu sarmal galaksidir. Galaksi içinde 20 Kasım 2009 tarihinde Tip IIP süpernova SN 2009lo keşfedilmiştir.
--------------------------------------------------------------------------------
Query: Kedi tuvalet kutularının temizliğinin önemi nedir ve kokuyu engellemek için neler yapılabilir?
Correct Answer: Bazen kum havuzu, kedi tuvalet kutusu veya kedi tuvaleti denilen kap kedilerin yanı sıra tavşanlar, yaban gelincik'ler, minyatür domuz'lar, küçük köpek'ler ve içgüdüsel olarak veya eğitim yoluyla böyle bir yerden yararlanan diğer evcil'ler için bir iç mekan dışkı ve idrar toplama kutusudur. Bir evde serbest dolaşımına izin verilen ancak metabolik atık için dışarı çıkamayan veya her zaman dışarı çıkmayan evcil hayvanlar için kullanılır. Bu hayvanların sahipleri, açık havadaki tehlikelere maruz kalma korkusuyla hayvanlarının dışarıda dolaşmalarına izin vermemeyi tercih eder. Ortalama, kapalı kedilerin ömrü 16.8 yıl iken, açık hava kedilerinin ömrü çok daha kısa, sadece 5.6 yıldır. Bu açık hava tehlikeleri arasında kötü hava durumu, yabani yaşam, trafik veya kedi immün yetmezlik virüsü gibi hastalıklar yer alır.
Vahşi doğada kediler, kolay gömmek için doğal olarak yumuşak veya kumlu toprağa dışkılarlar. Dışkılarını örtmek için patilerini geriye doğru süpürme hareketiyle kullanırlar. Bu içgüdüsel arzuyu harekete geçirmek için, kedi tuvalet kutusunun dibi genellikle 2 inç (5 cm) veya daha az kedi kumu ile doldurulur. Tuvalet kutusu dolgu maddesi, amonyak gibi nemi ve kokuları emen gevşek, tanecikli bir malzemedir. Bazı kum markaları, bu tür kokuları emmek için kabartma tozu içerir veya sahipleri, kutunun altında kedi kumunun altına, ince bir tabaka serpebilir. Altlık malzemesi ayrıca bir kedinin atıklarını gömmelerine izin vererek kokularını gizleme konusundaki içgüdüsel arzusunu da tatmin eder. En yaygın malzeme kildir, ancak geri dönüştürülmüş kâğıt "peletler" ve silika bazlı "kristal" çeşitleri de kullanılır. Bazen, sahibi kedinin doğal içgüdülerini harekete geçirmek istediğinde, doğal kir kullanılır.
Pisliğin içine döküldüğü kedi tuvalet kutusu, uygun şekilde temizlenmediğinde pis bir koku yayar. Tuvalet kutusundan kaçınmayı önlemek için, tuvalet kutusunun bodrum katı veya çamaşır odası gibi evin trafiğin az olduğu alanlarda tutulması tavsiye edilir. Çıkan kokuyu örtmeye veya azaltmaya yardımcı olmak için ticari olarak temin edilebilen özel tuvalet malzeme türleri vardır. Bunlar kabartma tozu, bitki özleri ve/veya kokulu kristaller içerirler. Hava girişi olan bir odada tutulursa, kokuyu evin geri kalanından izole etmek için fırın filtresine oda spreyi eklenebilir.

Retrieved Top-1: Bazen kum havuzu, kedi tuvalet kutusu veya kedi tuvaleti denilen kap kedilerin yanı sıra tavşanlar, yaban gelincik'ler, minyatür domuz'lar, küçük köpek'ler ve içgüdüsel olarak veya eğitim yoluyla böyle bir yerden yararlanan diğer evcil'ler için bir iç mekan dışkı ve idrar toplama kutusudur. Bir evde serbest dolaşımına izin verilen ancak metabolik atık için dışarı çıkamayan veya her zaman dışarı çıkmayan evcil hayvanlar için kullanılır. Bu hayvanların sahipleri, açık havadaki tehlikelere maruz kalma korkusuyla hayvanlarının dışarıda dolaşmalarına izin vermemeyi tercih eder. Ortalama, kapalı kedilerin ömrü 16.8 yıl iken, açık hava kedilerinin ömrü çok daha kısa, sadece 5.6 yıldır. Bu açık hava tehlikeleri arasında kötü hava durumu, yabani yaşam, trafik veya kedi immün yetmezlik virüsü gibi hastalıklar yer alır.
Vahşi doğada kediler, kolay gömmek için doğal olarak yumuşak veya kumlu toprağa dışkılarlar. Dışkılarını örtmek için patilerini geriye doğru süpürme hareketiyle kullanırlar. Bu içgüdüsel arzuyu harekete geçirmek için, kedi tuvalet kutusunun dibi genellikle 2 inç (5 cm) veya daha az kedi kumu ile doldurulur. Tuvalet kutusu dolgu maddesi, amonyak gibi nemi ve kokuları emen gevşek, tanecikli bir malzemedir. Bazı kum markaları, bu tür kokuları emmek için kabartma tozu içerir veya sahipleri, kutunun altında kedi kumunun altına, ince bir tabaka serpebilir. Altlık malzemesi ayrıca bir kedinin atıklarını gömmelerine izin vererek kokularını gizleme konusundaki içgüdüsel arzusunu da tatmin eder. En yaygın malzeme kildir, ancak geri dönüştürülmüş kâğıt "peletler" ve silika bazlı "kristal" çeşitleri de kullanılır. Bazen, sahibi kedinin doğal içgüdülerini harekete geçirmek istediğinde, doğal kir kullanılır.
Pisliğin içine döküldüğü kedi tuvalet kutusu, uygun şekilde temizlenmediğinde pis bir koku yayar. Tuvalet kutusundan kaçınmayı önlemek için, tuvalet kutusunun bodrum katı veya çamaşır odası gibi evin trafiğin az olduğu alanlarda tutulması tavsiye edilir. Çıkan kokuyu örtmeye veya azaltmaya yardımcı olmak için ticari olarak temin edilebilen özel tuvalet malzeme türleri vardır. Bunlar kabartma tozu, bitki özleri ve/veya kokulu kristaller içerirler. Hava girişi olan bir odada tutulursa, kokuyu evin geri kalanından izole etmek için fırın filtresine oda spreyi eklenebilir.

Retrieved Top-5:
  1. Bazen kum havuzu, kedi tuvalet kutusu veya kedi tuvaleti denilen kap kedilerin yanı sıra tavşanlar, yaban gelincik'ler, minyatür domuz'lar, küçük köpek'ler ve içgüdüsel olarak veya eğitim yoluyla böyle bir yerden yararlanan diğer evcil'ler için bir iç mekan dışkı ve idrar toplama kutusudur. Bir evde serbest dolaşımına izin verilen ancak metabolik atık için dışarı çıkamayan veya her zaman dışarı çıkmayan evcil hayvanlar için kullanılır. Bu hayvanların sahipleri, açık havadaki tehlikelere maruz kalma korkusuyla hayvanlarının dışarıda dolaşmalarına izin vermemeyi tercih eder. Ortalama, kapalı kedilerin ömrü 16.8 yıl iken, açık hava kedilerinin ömrü çok daha kısa, sadece 5.6 yıldır. Bu açık hava tehlikeleri arasında kötü hava durumu, yabani yaşam, trafik veya kedi immün yetmezlik virüsü gibi hastalıklar yer alır.
Vahşi doğada kediler, kolay gömmek için doğal olarak yumuşak veya kumlu toprağa dışkılarlar. Dışkılarını örtmek için patilerini geriye doğru süpürme hareketiyle kullanırlar. Bu içgüdüsel arzuyu harekete geçirmek için, kedi tuvalet kutusunun dibi genellikle 2 inç (5 cm) veya daha az kedi kumu ile doldurulur. Tuvalet kutusu dolgu maddesi, amonyak gibi nemi ve kokuları emen gevşek, tanecikli bir malzemedir. Bazı kum markaları, bu tür kokuları emmek için kabartma tozu içerir veya sahipleri, kutunun altında kedi kumunun altına, ince bir tabaka serpebilir. Altlık malzemesi ayrıca bir kedinin atıklarını gömmelerine izin vererek kokularını gizleme konusundaki içgüdüsel arzusunu da tatmin eder. En yaygın malzeme kildir, ancak geri dönüştürülmüş kâğıt "peletler" ve silika bazlı "kristal" çeşitleri de kullanılır. Bazen, sahibi kedinin doğal içgüdülerini harekete geçirmek istediğinde, doğal kir kullanılır.
Pisliğin içine döküldüğü kedi tuvalet kutusu, uygun şekilde temizlenmediğinde pis bir koku yayar. Tuvalet kutusundan kaçınmayı önlemek için, tuvalet kutusunun bodrum katı veya çamaşır odası gibi evin trafiğin az olduğu alanlarda tutulması tavsiye edilir. Çıkan kokuyu örtmeye veya azaltmaya yardımcı olmak için ticari olarak temin edilebilen özel tuvalet malzeme türleri vardır. Bunlar kabartma tozu, bitki özleri ve/veya kokulu kristaller içerirler. Hava girişi olan bir odada tutulursa, kokuyu evin geri kalanından izole etmek için fırın filtresine oda spreyi eklenebilir.

  2. Dilivium, bir jeoloji terimidir. Sel ve taşkın sularının yüzeysel akışı sırasında bünyesinde taşıdığı kil ve benzeri alüvyonları yavaş ve istikrarlı bir şekilde biriktirmesiyle oluşan kayaçlardır. Bu terim eskiden Nuh tufanının neden olduğu sanılan kaya kil katmanlarına verilirdi.
20. yüzyılın sonlarında Rus coğrafyacı Alexei Rudoy dilivium terimini Altay havzası dağlar asındaki Buzul Çağı dev buzul barajı göllerinin katastrofik patlamaları sonucu oluşan katmanların tanımı için önermiştir. Bu göllerin en genişleri, Chuya ve Kuray, yüzlerce kilometre su hacmine sahipti ve bunların zirve hidrografi akış hızındaki tahliye oranı, Kuzey Amerika’daki meşhur Pleistosen Lake Missoula selinin azami oranlarını aşmıştır.

  3. Carl Sagan Award for Public Understanding of Science, Council of Scientific Society Presidents tarafından verilen  halk tarafından tanınmış araştırmacı, bilim insanları, eğitimciler ve halka bilimi anlamasını sağlayan kişilere verilir. Ödül ilk olarak ödülle de onuruna aynı adı taşıyan Carl Sagan tarafından verildi.
  4. Sicim teorisi, parçacık fiziğinde, kuantum mekaniği ile Einstein'in genel görelilik kuramını birleştiren bir teori. "Sicim" adı, klasik yaklaşımda "sıfır boyutlu noktalar" şeklinde tarif edilen atomaltı parçacıkların, aslında "bir boyutlu ve ipliksi varlıklar" olabileceği varsayımına dayanır.
Sicim kuramı, belirli bir biçimde titreşen ipliksilerin, kütle ve yük gibi özelliklere sahip parçacıklar gibi davranabileceğini söyler. 1980'lerde fizikçiler, sicim kuramının doğadaki başlıca dört güç (kütleçekimi, elektromanyetizma, güçlü etkileşim [kuvvetli nükleer güç] ve zayıf etkileşim [zayıf nükleer güç]) ile maddenin tüm türlerini bir kuantum mekanik modelinde (uzun süredir beklenen "birleşik alan teorisi") birleştirme potansiyeline sahip olduğunu fark ettiler.
Sicim kuramı hızla gelişen ve üzerinde çok çalışılan bir alan olmakla birlikte, henüz deneysel gözlemi mümkün olmamış, matematiksel bir modeldir.

  5. Ordnungspolizei (kısaca: OrPo veya Orpo, üniformasının renginden dolayı Grüne Polizei), Nazi Almanyası'nın normal polisi.
Nazi Almanyası döneminde özellikle 1936 - 1945 yılları arasında Sicherheitspolizei (SiPo) ile birlikte rejimi korumakta önemli rolü oynadı.
Milyonlarca Yahudi ve Sovyet savaş esiri Ordnungspolizei mensupları tarafından infaz edildi.

--------------------------------------------------------------------------------